
shui：     文件格式 elf32-i386


Disassembly of section .text:

00100000 <isr0>:
  100000:	fa                   	cli    
  100001:	6a 00                	push   $0x0
  100003:	6a 00                	push   $0x0
  100005:	e9 fc 00 00 00       	jmp    100106 <isr_common_stub>

0010000a <isr1>:
  10000a:	fa                   	cli    
  10000b:	6a 00                	push   $0x0
  10000d:	6a 01                	push   $0x1
  10000f:	e9 f2 00 00 00       	jmp    100106 <isr_common_stub>

00100014 <isr2>:
  100014:	fa                   	cli    
  100015:	6a 00                	push   $0x0
  100017:	6a 02                	push   $0x2
  100019:	e9 e8 00 00 00       	jmp    100106 <isr_common_stub>

0010001e <isr3>:
  10001e:	fa                   	cli    
  10001f:	6a 00                	push   $0x0
  100021:	6a 03                	push   $0x3
  100023:	e9 de 00 00 00       	jmp    100106 <isr_common_stub>

00100028 <isr4>:
  100028:	fa                   	cli    
  100029:	6a 00                	push   $0x0
  10002b:	6a 04                	push   $0x4
  10002d:	e9 d4 00 00 00       	jmp    100106 <isr_common_stub>

00100032 <isr5>:
  100032:	fa                   	cli    
  100033:	6a 00                	push   $0x0
  100035:	6a 05                	push   $0x5
  100037:	e9 ca 00 00 00       	jmp    100106 <isr_common_stub>

0010003c <isr6>:
  10003c:	fa                   	cli    
  10003d:	6a 00                	push   $0x0
  10003f:	6a 06                	push   $0x6
  100041:	e9 c0 00 00 00       	jmp    100106 <isr_common_stub>

00100046 <isr7>:
  100046:	fa                   	cli    
  100047:	6a 00                	push   $0x0
  100049:	6a 07                	push   $0x7
  10004b:	e9 b6 00 00 00       	jmp    100106 <isr_common_stub>

00100050 <isr8>:
  100050:	fa                   	cli    
  100051:	6a 08                	push   $0x8
  100053:	e9 ae 00 00 00       	jmp    100106 <isr_common_stub>

00100058 <isr9>:
  100058:	fa                   	cli    
  100059:	6a 00                	push   $0x0
  10005b:	6a 09                	push   $0x9
  10005d:	e9 a4 00 00 00       	jmp    100106 <isr_common_stub>

00100062 <isr10>:
  100062:	fa                   	cli    
  100063:	6a 0a                	push   $0xa
  100065:	e9 9c 00 00 00       	jmp    100106 <isr_common_stub>

0010006a <isr11>:
  10006a:	fa                   	cli    
  10006b:	6a 0b                	push   $0xb
  10006d:	e9 94 00 00 00       	jmp    100106 <isr_common_stub>

00100072 <isr12>:
  100072:	fa                   	cli    
  100073:	6a 0c                	push   $0xc
  100075:	e9 8c 00 00 00       	jmp    100106 <isr_common_stub>

0010007a <isr13>:
  10007a:	fa                   	cli    
  10007b:	6a 0d                	push   $0xd
  10007d:	e9 84 00 00 00       	jmp    100106 <isr_common_stub>

00100082 <isr14>:
  100082:	fa                   	cli    
  100083:	6a 0e                	push   $0xe
  100085:	eb 7f                	jmp    100106 <isr_common_stub>

00100087 <isr15>:
  100087:	fa                   	cli    
  100088:	6a 00                	push   $0x0
  10008a:	6a 0f                	push   $0xf
  10008c:	eb 78                	jmp    100106 <isr_common_stub>

0010008e <isr16>:
  10008e:	fa                   	cli    
  10008f:	6a 00                	push   $0x0
  100091:	6a 10                	push   $0x10
  100093:	eb 71                	jmp    100106 <isr_common_stub>

00100095 <isr17>:
  100095:	fa                   	cli    
  100096:	6a 11                	push   $0x11
  100098:	eb 6c                	jmp    100106 <isr_common_stub>

0010009a <isr18>:
  10009a:	fa                   	cli    
  10009b:	6a 00                	push   $0x0
  10009d:	6a 12                	push   $0x12
  10009f:	eb 65                	jmp    100106 <isr_common_stub>

001000a1 <isr19>:
  1000a1:	fa                   	cli    
  1000a2:	6a 00                	push   $0x0
  1000a4:	6a 13                	push   $0x13
  1000a6:	eb 5e                	jmp    100106 <isr_common_stub>

001000a8 <isr20>:
  1000a8:	fa                   	cli    
  1000a9:	6a 00                	push   $0x0
  1000ab:	6a 14                	push   $0x14
  1000ad:	eb 57                	jmp    100106 <isr_common_stub>

001000af <isr21>:
  1000af:	fa                   	cli    
  1000b0:	6a 00                	push   $0x0
  1000b2:	6a 15                	push   $0x15
  1000b4:	eb 50                	jmp    100106 <isr_common_stub>

001000b6 <isr22>:
  1000b6:	fa                   	cli    
  1000b7:	6a 00                	push   $0x0
  1000b9:	6a 16                	push   $0x16
  1000bb:	eb 49                	jmp    100106 <isr_common_stub>

001000bd <isr23>:
  1000bd:	fa                   	cli    
  1000be:	6a 00                	push   $0x0
  1000c0:	6a 17                	push   $0x17
  1000c2:	eb 42                	jmp    100106 <isr_common_stub>

001000c4 <isr24>:
  1000c4:	fa                   	cli    
  1000c5:	6a 00                	push   $0x0
  1000c7:	6a 18                	push   $0x18
  1000c9:	eb 3b                	jmp    100106 <isr_common_stub>

001000cb <isr25>:
  1000cb:	fa                   	cli    
  1000cc:	6a 00                	push   $0x0
  1000ce:	6a 19                	push   $0x19
  1000d0:	eb 34                	jmp    100106 <isr_common_stub>

001000d2 <isr26>:
  1000d2:	fa                   	cli    
  1000d3:	6a 00                	push   $0x0
  1000d5:	6a 1a                	push   $0x1a
  1000d7:	eb 2d                	jmp    100106 <isr_common_stub>

001000d9 <isr27>:
  1000d9:	fa                   	cli    
  1000da:	6a 00                	push   $0x0
  1000dc:	6a 1b                	push   $0x1b
  1000de:	eb 26                	jmp    100106 <isr_common_stub>

001000e0 <isr28>:
  1000e0:	fa                   	cli    
  1000e1:	6a 00                	push   $0x0
  1000e3:	6a 1c                	push   $0x1c
  1000e5:	eb 1f                	jmp    100106 <isr_common_stub>

001000e7 <isr29>:
  1000e7:	fa                   	cli    
  1000e8:	6a 00                	push   $0x0
  1000ea:	6a 1d                	push   $0x1d
  1000ec:	eb 18                	jmp    100106 <isr_common_stub>

001000ee <isr30>:
  1000ee:	fa                   	cli    
  1000ef:	6a 00                	push   $0x0
  1000f1:	6a 1e                	push   $0x1e
  1000f3:	eb 11                	jmp    100106 <isr_common_stub>

001000f5 <isr31>:
  1000f5:	fa                   	cli    
  1000f6:	6a 00                	push   $0x0
  1000f8:	6a 1f                	push   $0x1f
  1000fa:	eb 0a                	jmp    100106 <isr_common_stub>

001000fc <isr255>:
  1000fc:	fa                   	cli    
  1000fd:	6a 00                	push   $0x0
  1000ff:	68 ff 00 00 00       	push   $0xff
  100104:	eb 00                	jmp    100106 <isr_common_stub>

00100106 <isr_common_stub>:
  100106:	60                   	pusha  
  100107:	66 8c d8             	mov    %ds,%ax
  10010a:	50                   	push   %eax
  10010b:	66 b8 10 00          	mov    $0x10,%ax
  10010f:	8e d8                	mov    %eax,%ds
  100111:	8e c0                	mov    %eax,%es
  100113:	8e e0                	mov    %eax,%fs
  100115:	8e e8                	mov    %eax,%gs
  100117:	8e d0                	mov    %eax,%ss
  100119:	54                   	push   %esp
  10011a:	e8 f0 05 00 00       	call   10070f <isr_handler>
  10011f:	83 c4 04             	add    $0x4,%esp
  100122:	5b                   	pop    %ebx
  100123:	8e db                	mov    %ebx,%ds
  100125:	8e c3                	mov    %ebx,%es
  100127:	8e e3                	mov    %ebx,%fs
  100129:	8e eb                	mov    %ebx,%gs
  10012b:	8e d3                	mov    %ebx,%ss
  10012d:	61                   	popa   
  10012e:	83 c4 08             	add    $0x8,%esp
  100131:	cf                   	iret   

00100132 <idt_flush>:
  100132:	8b 44 24 04          	mov    0x4(%esp),%eax
  100136:	0f 01 18             	lidtl  (%eax)
  100139:	c3                   	ret    

0010013a <idt_flush.end>:
  10013a:	66 90                	xchg   %ax,%ax
  10013c:	66 90                	xchg   %ax,%ax
  10013e:	66 90                	xchg   %ax,%ax
  100140:	02 b0 ad 1b 03 00    	add    0x31bad(%eax),%dh
  100146:	00 00                	add    %al,(%eax)
  100148:	fb                   	sti    
  100149:	4f                   	dec    %edi
  10014a:	52                   	push   %edx
  10014b:	e4 fa                	in     $0xfa,%al

0010014c <start>:
  10014c:	fa                   	cli    
  10014d:	bc 03 80 00 00       	mov    $0x8003,%esp
  100152:	bd 00 00 00 00       	mov    $0x0,%ebp
  100157:	81 e4 f0 ff ff 0f    	and    $0xffffff0,%esp
  10015d:	89 1d 00 b0 10 00    	mov    %ebx,0x10b000
  100163:	e8 04 12 00 00       	call   10136c <entry>

00100168 <stop>:
  100168:	f4                   	hlt    
  100169:	eb fd                	jmp    100168 <stop>
  10016b:	66 90                	xchg   %ax,%ax
  10016d:	66 90                	xchg   %ax,%ax
  10016f:	90                   	nop

00100170 <gdt_flush>:
  100170:	8b 44 24 04          	mov    0x4(%esp),%eax
  100174:	0f 01 10             	lgdtl  (%eax)
  100177:	66 b8 10 00          	mov    $0x10,%ax
  10017b:	8e d8                	mov    %eax,%ds
  10017d:	8e c0                	mov    %eax,%es
  10017f:	8e e0                	mov    %eax,%fs
  100181:	8e e8                	mov    %eax,%gs
  100183:	8e d0                	mov    %eax,%ss
  100185:	ea 8c 01 10 00 08 00 	ljmp   $0x8,$0x10018c

0010018c <gdt_flush.flush>:
  10018c:	c3                   	ret    
  10018d:	66 90                	xchg   %ax,%ax
  10018f:	90                   	nop

00100190 <init_idt>:
  100190:	55                   	push   %ebp
  100191:	89 e5                	mov    %esp,%ebp
  100193:	83 ec 18             	sub    $0x18,%esp
  100196:	c7 44 24 04 00 04 00 	movl   $0x400,0x4(%esp)
  10019d:	00 
  10019e:	c7 04 24 20 c8 10 00 	movl   $0x10c820,(%esp)
  1001a5:	e8 6b 08 00 00       	call   100a15 <bzer>
  1001aa:	66 c7 05 00 c0 10 00 	movw   $0x7ff,0x10c000
  1001b1:	ff 07 
  1001b3:	b8 20 c0 10 00       	mov    $0x10c020,%eax
  1001b8:	0f b6 c0             	movzbl %al,%eax
  1001bb:	a3 02 c0 10 00       	mov    %eax,0x10c002
  1001c0:	c7 44 24 04 00 08 00 	movl   $0x800,0x4(%esp)
  1001c7:	00 
  1001c8:	c7 04 24 20 c0 10 00 	movl   $0x10c020,(%esp)
  1001cf:	e8 41 08 00 00       	call   100a15 <bzer>
  1001d4:	b8 00 00 10 00       	mov    $0x100000,%eax
  1001d9:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1001e0:	00 
  1001e1:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1001e8:	00 
  1001e9:	89 44 24 04          	mov    %eax,0x4(%esp)
  1001ed:	c7 04 24 00 00 00 00 	movl   $0x0,(%esp)
  1001f4:	e8 af 04 00 00       	call   1006a8 <idt_set_gate>
  1001f9:	b8 0a 00 10 00       	mov    $0x10000a,%eax
  1001fe:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100205:	00 
  100206:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  10020d:	00 
  10020e:	89 44 24 04          	mov    %eax,0x4(%esp)
  100212:	c7 04 24 01 00 00 00 	movl   $0x1,(%esp)
  100219:	e8 8a 04 00 00       	call   1006a8 <idt_set_gate>
  10021e:	b8 14 00 10 00       	mov    $0x100014,%eax
  100223:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10022a:	00 
  10022b:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100232:	00 
  100233:	89 44 24 04          	mov    %eax,0x4(%esp)
  100237:	c7 04 24 02 00 00 00 	movl   $0x2,(%esp)
  10023e:	e8 65 04 00 00       	call   1006a8 <idt_set_gate>
  100243:	b8 1e 00 10 00       	mov    $0x10001e,%eax
  100248:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10024f:	00 
  100250:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100257:	00 
  100258:	89 44 24 04          	mov    %eax,0x4(%esp)
  10025c:	c7 04 24 03 00 00 00 	movl   $0x3,(%esp)
  100263:	e8 40 04 00 00       	call   1006a8 <idt_set_gate>
  100268:	b8 28 00 10 00       	mov    $0x100028,%eax
  10026d:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100274:	00 
  100275:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  10027c:	00 
  10027d:	89 44 24 04          	mov    %eax,0x4(%esp)
  100281:	c7 04 24 04 00 00 00 	movl   $0x4,(%esp)
  100288:	e8 1b 04 00 00       	call   1006a8 <idt_set_gate>
  10028d:	b8 32 00 10 00       	mov    $0x100032,%eax
  100292:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100299:	00 
  10029a:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1002a1:	00 
  1002a2:	89 44 24 04          	mov    %eax,0x4(%esp)
  1002a6:	c7 04 24 05 00 00 00 	movl   $0x5,(%esp)
  1002ad:	e8 f6 03 00 00       	call   1006a8 <idt_set_gate>
  1002b2:	b8 3c 00 10 00       	mov    $0x10003c,%eax
  1002b7:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1002be:	00 
  1002bf:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1002c6:	00 
  1002c7:	89 44 24 04          	mov    %eax,0x4(%esp)
  1002cb:	c7 04 24 06 00 00 00 	movl   $0x6,(%esp)
  1002d2:	e8 d1 03 00 00       	call   1006a8 <idt_set_gate>
  1002d7:	b8 46 00 10 00       	mov    $0x100046,%eax
  1002dc:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1002e3:	00 
  1002e4:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1002eb:	00 
  1002ec:	89 44 24 04          	mov    %eax,0x4(%esp)
  1002f0:	c7 04 24 07 00 00 00 	movl   $0x7,(%esp)
  1002f7:	e8 ac 03 00 00       	call   1006a8 <idt_set_gate>
  1002fc:	b8 50 00 10 00       	mov    $0x100050,%eax
  100301:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100308:	00 
  100309:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100310:	00 
  100311:	89 44 24 04          	mov    %eax,0x4(%esp)
  100315:	c7 04 24 08 00 00 00 	movl   $0x8,(%esp)
  10031c:	e8 87 03 00 00       	call   1006a8 <idt_set_gate>
  100321:	b8 58 00 10 00       	mov    $0x100058,%eax
  100326:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10032d:	00 
  10032e:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100335:	00 
  100336:	89 44 24 04          	mov    %eax,0x4(%esp)
  10033a:	c7 04 24 09 00 00 00 	movl   $0x9,(%esp)
  100341:	e8 62 03 00 00       	call   1006a8 <idt_set_gate>
  100346:	b8 62 00 10 00       	mov    $0x100062,%eax
  10034b:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100352:	00 
  100353:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  10035a:	00 
  10035b:	89 44 24 04          	mov    %eax,0x4(%esp)
  10035f:	c7 04 24 0a 00 00 00 	movl   $0xa,(%esp)
  100366:	e8 3d 03 00 00       	call   1006a8 <idt_set_gate>
  10036b:	b8 6a 00 10 00       	mov    $0x10006a,%eax
  100370:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100377:	00 
  100378:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  10037f:	00 
  100380:	89 44 24 04          	mov    %eax,0x4(%esp)
  100384:	c7 04 24 0b 00 00 00 	movl   $0xb,(%esp)
  10038b:	e8 18 03 00 00       	call   1006a8 <idt_set_gate>
  100390:	b8 72 00 10 00       	mov    $0x100072,%eax
  100395:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10039c:	00 
  10039d:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1003a4:	00 
  1003a5:	89 44 24 04          	mov    %eax,0x4(%esp)
  1003a9:	c7 04 24 0c 00 00 00 	movl   $0xc,(%esp)
  1003b0:	e8 f3 02 00 00       	call   1006a8 <idt_set_gate>
  1003b5:	b8 7a 00 10 00       	mov    $0x10007a,%eax
  1003ba:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1003c1:	00 
  1003c2:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1003c9:	00 
  1003ca:	89 44 24 04          	mov    %eax,0x4(%esp)
  1003ce:	c7 04 24 0d 00 00 00 	movl   $0xd,(%esp)
  1003d5:	e8 ce 02 00 00       	call   1006a8 <idt_set_gate>
  1003da:	b8 82 00 10 00       	mov    $0x100082,%eax
  1003df:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1003e6:	00 
  1003e7:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1003ee:	00 
  1003ef:	89 44 24 04          	mov    %eax,0x4(%esp)
  1003f3:	c7 04 24 0e 00 00 00 	movl   $0xe,(%esp)
  1003fa:	e8 a9 02 00 00       	call   1006a8 <idt_set_gate>
  1003ff:	b8 87 00 10 00       	mov    $0x100087,%eax
  100404:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10040b:	00 
  10040c:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100413:	00 
  100414:	89 44 24 04          	mov    %eax,0x4(%esp)
  100418:	c7 04 24 0f 00 00 00 	movl   $0xf,(%esp)
  10041f:	e8 84 02 00 00       	call   1006a8 <idt_set_gate>
  100424:	b8 8e 00 10 00       	mov    $0x10008e,%eax
  100429:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100430:	00 
  100431:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100438:	00 
  100439:	89 44 24 04          	mov    %eax,0x4(%esp)
  10043d:	c7 04 24 10 00 00 00 	movl   $0x10,(%esp)
  100444:	e8 5f 02 00 00       	call   1006a8 <idt_set_gate>
  100449:	b8 95 00 10 00       	mov    $0x100095,%eax
  10044e:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100455:	00 
  100456:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  10045d:	00 
  10045e:	89 44 24 04          	mov    %eax,0x4(%esp)
  100462:	c7 04 24 11 00 00 00 	movl   $0x11,(%esp)
  100469:	e8 3a 02 00 00       	call   1006a8 <idt_set_gate>
  10046e:	b8 9a 00 10 00       	mov    $0x10009a,%eax
  100473:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10047a:	00 
  10047b:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100482:	00 
  100483:	89 44 24 04          	mov    %eax,0x4(%esp)
  100487:	c7 04 24 12 00 00 00 	movl   $0x12,(%esp)
  10048e:	e8 15 02 00 00       	call   1006a8 <idt_set_gate>
  100493:	b8 a1 00 10 00       	mov    $0x1000a1,%eax
  100498:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10049f:	00 
  1004a0:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1004a7:	00 
  1004a8:	89 44 24 04          	mov    %eax,0x4(%esp)
  1004ac:	c7 04 24 13 00 00 00 	movl   $0x13,(%esp)
  1004b3:	e8 f0 01 00 00       	call   1006a8 <idt_set_gate>
  1004b8:	b8 a8 00 10 00       	mov    $0x1000a8,%eax
  1004bd:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1004c4:	00 
  1004c5:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1004cc:	00 
  1004cd:	89 44 24 04          	mov    %eax,0x4(%esp)
  1004d1:	c7 04 24 14 00 00 00 	movl   $0x14,(%esp)
  1004d8:	e8 cb 01 00 00       	call   1006a8 <idt_set_gate>
  1004dd:	b8 af 00 10 00       	mov    $0x1000af,%eax
  1004e2:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1004e9:	00 
  1004ea:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1004f1:	00 
  1004f2:	89 44 24 04          	mov    %eax,0x4(%esp)
  1004f6:	c7 04 24 15 00 00 00 	movl   $0x15,(%esp)
  1004fd:	e8 a6 01 00 00       	call   1006a8 <idt_set_gate>
  100502:	b8 b6 00 10 00       	mov    $0x1000b6,%eax
  100507:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10050e:	00 
  10050f:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100516:	00 
  100517:	89 44 24 04          	mov    %eax,0x4(%esp)
  10051b:	c7 04 24 16 00 00 00 	movl   $0x16,(%esp)
  100522:	e8 81 01 00 00       	call   1006a8 <idt_set_gate>
  100527:	b8 bd 00 10 00       	mov    $0x1000bd,%eax
  10052c:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100533:	00 
  100534:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  10053b:	00 
  10053c:	89 44 24 04          	mov    %eax,0x4(%esp)
  100540:	c7 04 24 17 00 00 00 	movl   $0x17,(%esp)
  100547:	e8 5c 01 00 00       	call   1006a8 <idt_set_gate>
  10054c:	b8 c4 00 10 00       	mov    $0x1000c4,%eax
  100551:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100558:	00 
  100559:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100560:	00 
  100561:	89 44 24 04          	mov    %eax,0x4(%esp)
  100565:	c7 04 24 18 00 00 00 	movl   $0x18,(%esp)
  10056c:	e8 37 01 00 00       	call   1006a8 <idt_set_gate>
  100571:	b8 cb 00 10 00       	mov    $0x1000cb,%eax
  100576:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10057d:	00 
  10057e:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100585:	00 
  100586:	89 44 24 04          	mov    %eax,0x4(%esp)
  10058a:	c7 04 24 19 00 00 00 	movl   $0x19,(%esp)
  100591:	e8 12 01 00 00       	call   1006a8 <idt_set_gate>
  100596:	b8 d2 00 10 00       	mov    $0x1000d2,%eax
  10059b:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1005a2:	00 
  1005a3:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1005aa:	00 
  1005ab:	89 44 24 04          	mov    %eax,0x4(%esp)
  1005af:	c7 04 24 1a 00 00 00 	movl   $0x1a,(%esp)
  1005b6:	e8 ed 00 00 00       	call   1006a8 <idt_set_gate>
  1005bb:	b8 d9 00 10 00       	mov    $0x1000d9,%eax
  1005c0:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1005c7:	00 
  1005c8:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1005cf:	00 
  1005d0:	89 44 24 04          	mov    %eax,0x4(%esp)
  1005d4:	c7 04 24 1b 00 00 00 	movl   $0x1b,(%esp)
  1005db:	e8 c8 00 00 00       	call   1006a8 <idt_set_gate>
  1005e0:	b8 e0 00 10 00       	mov    $0x1000e0,%eax
  1005e5:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  1005ec:	00 
  1005ed:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  1005f4:	00 
  1005f5:	89 44 24 04          	mov    %eax,0x4(%esp)
  1005f9:	c7 04 24 1c 00 00 00 	movl   $0x1c,(%esp)
  100600:	e8 a3 00 00 00       	call   1006a8 <idt_set_gate>
  100605:	b8 e7 00 10 00       	mov    $0x1000e7,%eax
  10060a:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100611:	00 
  100612:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100619:	00 
  10061a:	89 44 24 04          	mov    %eax,0x4(%esp)
  10061e:	c7 04 24 1d 00 00 00 	movl   $0x1d,(%esp)
  100625:	e8 7e 00 00 00       	call   1006a8 <idt_set_gate>
  10062a:	b8 ee 00 10 00       	mov    $0x1000ee,%eax
  10062f:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100636:	00 
  100637:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  10063e:	00 
  10063f:	89 44 24 04          	mov    %eax,0x4(%esp)
  100643:	c7 04 24 1e 00 00 00 	movl   $0x1e,(%esp)
  10064a:	e8 59 00 00 00       	call   1006a8 <idt_set_gate>
  10064f:	b8 f5 00 10 00       	mov    $0x1000f5,%eax
  100654:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  10065b:	00 
  10065c:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100663:	00 
  100664:	89 44 24 04          	mov    %eax,0x4(%esp)
  100668:	c7 04 24 1f 00 00 00 	movl   $0x1f,(%esp)
  10066f:	e8 34 00 00 00       	call   1006a8 <idt_set_gate>
  100674:	b8 fc 00 10 00       	mov    $0x1000fc,%eax
  100679:	c7 44 24 0c 8e 00 00 	movl   $0x8e,0xc(%esp)
  100680:	00 
  100681:	c7 44 24 08 08 00 00 	movl   $0x8,0x8(%esp)
  100688:	00 
  100689:	89 44 24 04          	mov    %eax,0x4(%esp)
  10068d:	c7 04 24 ff 00 00 00 	movl   $0xff,(%esp)
  100694:	e8 0f 00 00 00       	call   1006a8 <idt_set_gate>
  100699:	b8 00 c0 10 00       	mov    $0x10c000,%eax
  10069e:	89 04 24             	mov    %eax,(%esp)
  1006a1:	e8 8c fa ff ff       	call   100132 <idt_flush>
  1006a6:	c9                   	leave  
  1006a7:	c3                   	ret    

001006a8 <idt_set_gate>:
  1006a8:	55                   	push   %ebp
  1006a9:	89 e5                	mov    %esp,%ebp
  1006ab:	83 ec 0c             	sub    $0xc,%esp
  1006ae:	8b 4d 08             	mov    0x8(%ebp),%ecx
  1006b1:	8b 55 10             	mov    0x10(%ebp),%edx
  1006b4:	8b 45 14             	mov    0x14(%ebp),%eax
  1006b7:	88 4d fc             	mov    %cl,-0x4(%ebp)
  1006ba:	66 89 55 f8          	mov    %dx,-0x8(%ebp)
  1006be:	88 45 f4             	mov    %al,-0xc(%ebp)
  1006c1:	0f b6 45 fc          	movzbl -0x4(%ebp),%eax
  1006c5:	8b 55 0c             	mov    0xc(%ebp),%edx
  1006c8:	66 89 14 c5 20 c0 10 	mov    %dx,0x10c020(,%eax,8)
  1006cf:	00 
  1006d0:	0f b6 45 fc          	movzbl -0x4(%ebp),%eax
  1006d4:	8b 55 0c             	mov    0xc(%ebp),%edx
  1006d7:	c1 ea 10             	shr    $0x10,%edx
  1006da:	66 89 14 c5 26 c0 10 	mov    %dx,0x10c026(,%eax,8)
  1006e1:	00 
  1006e2:	0f b6 45 fc          	movzbl -0x4(%ebp),%eax
  1006e6:	0f b7 55 f8          	movzwl -0x8(%ebp),%edx
  1006ea:	66 89 14 c5 22 c0 10 	mov    %dx,0x10c022(,%eax,8)
  1006f1:	00 
  1006f2:	0f b6 45 fc          	movzbl -0x4(%ebp),%eax
  1006f6:	c6 04 c5 24 c0 10 00 	movb   $0x0,0x10c024(,%eax,8)
  1006fd:	00 
  1006fe:	0f b6 45 fc          	movzbl -0x4(%ebp),%eax
  100702:	0f b6 55 f4          	movzbl -0xc(%ebp),%edx
  100706:	88 14 c5 25 c0 10 00 	mov    %dl,0x10c025(,%eax,8)
  10070d:	c9                   	leave  
  10070e:	c3                   	ret    

0010070f <isr_handler>:
  10070f:	55                   	push   %ebp
  100710:	89 e5                	mov    %esp,%ebp
  100712:	83 ec 18             	sub    $0x18,%esp
  100715:	8b 45 08             	mov    0x8(%ebp),%eax
  100718:	8b 40 20             	mov    0x20(%eax),%eax
  10071b:	8b 04 85 20 c8 10 00 	mov    0x10c820(,%eax,4),%eax
  100722:	85 c0                	test   %eax,%eax
  100724:	74 17                	je     10073d <isr_handler+0x2e>
  100726:	8b 45 08             	mov    0x8(%ebp),%eax
  100729:	8b 40 20             	mov    0x20(%eax),%eax
  10072c:	8b 04 85 20 c8 10 00 	mov    0x10c820(,%eax,4),%eax
  100733:	8b 55 08             	mov    0x8(%ebp),%edx
  100736:	89 14 24             	mov    %edx,(%esp)
  100739:	ff d0                	call   *%eax
  10073b:	eb 16                	jmp    100753 <isr_handler+0x44>
  10073d:	8b 45 08             	mov    0x8(%ebp),%eax
  100740:	8b 40 20             	mov    0x20(%eax),%eax
  100743:	89 44 24 04          	mov    %eax,0x4(%esp)
  100747:	c7 04 24 20 24 10 00 	movl   $0x102420,(%esp)
  10074e:	e8 f4 07 00 00       	call   100f47 <printk>
  100753:	c9                   	leave  
  100754:	c3                   	ret    

00100755 <registers_interrupt_handler>:
  100755:	55                   	push   %ebp
  100756:	89 e5                	mov    %esp,%ebp
  100758:	83 ec 04             	sub    $0x4,%esp
  10075b:	8b 45 08             	mov    0x8(%ebp),%eax
  10075e:	88 45 fc             	mov    %al,-0x4(%ebp)
  100761:	0f b6 45 fc          	movzbl -0x4(%ebp),%eax
  100765:	8b 55 0c             	mov    0xc(%ebp),%edx
  100768:	89 14 85 20 c8 10 00 	mov    %edx,0x10c820(,%eax,4)
  10076f:	c9                   	leave  
  100770:	c3                   	ret    
  100771:	66 90                	xchg   %ax,%ax
  100773:	90                   	nop

00100774 <elf_form_multiboot>:
  100774:	55                   	push   %ebp
  100775:	89 e5                	mov    %esp,%ebp
  100777:	83 ec 38             	sub    $0x38,%esp
  10077a:	8b 45 0c             	mov    0xc(%ebp),%eax
  10077d:	8b 40 24             	mov    0x24(%eax),%eax
  100780:	89 45 f0             	mov    %eax,-0x10(%ebp)
  100783:	8b 45 0c             	mov    0xc(%ebp),%eax
  100786:	8b 50 28             	mov    0x28(%eax),%edx
  100789:	89 d0                	mov    %edx,%eax
  10078b:	c1 e0 02             	shl    $0x2,%eax
  10078e:	01 d0                	add    %edx,%eax
  100790:	c1 e0 03             	shl    $0x3,%eax
  100793:	89 c2                	mov    %eax,%edx
  100795:	8b 45 f0             	mov    -0x10(%ebp),%eax
  100798:	01 d0                	add    %edx,%eax
  10079a:	8b 40 0c             	mov    0xc(%eax),%eax
  10079d:	89 45 ec             	mov    %eax,-0x14(%ebp)
  1007a0:	c7 45 f4 00 00 00 00 	movl   $0x0,-0xc(%ebp)
  1007a7:	e9 b8 00 00 00       	jmp    100864 <elf_form_multiboot+0xf0>
  1007ac:	8b 55 f4             	mov    -0xc(%ebp),%edx
  1007af:	89 d0                	mov    %edx,%eax
  1007b1:	c1 e0 02             	shl    $0x2,%eax
  1007b4:	01 d0                	add    %edx,%eax
  1007b6:	c1 e0 03             	shl    $0x3,%eax
  1007b9:	89 c2                	mov    %eax,%edx
  1007bb:	8b 45 f0             	mov    -0x10(%ebp),%eax
  1007be:	01 d0                	add    %edx,%eax
  1007c0:	8b 10                	mov    (%eax),%edx
  1007c2:	8b 45 ec             	mov    -0x14(%ebp),%eax
  1007c5:	01 d0                	add    %edx,%eax
  1007c7:	89 45 e8             	mov    %eax,-0x18(%ebp)
  1007ca:	c7 44 24 04 38 24 10 	movl   $0x102438,0x4(%esp)
  1007d1:	00 
  1007d2:	8b 45 e8             	mov    -0x18(%ebp),%eax
  1007d5:	89 04 24             	mov    %eax,(%esp)
  1007d8:	e8 ae 02 00 00       	call   100a8b <strcmp>
  1007dd:	85 c0                	test   %eax,%eax
  1007df:	75 34                	jne    100815 <elf_form_multiboot+0xa1>
  1007e1:	8b 55 f4             	mov    -0xc(%ebp),%edx
  1007e4:	89 d0                	mov    %edx,%eax
  1007e6:	c1 e0 02             	shl    $0x2,%eax
  1007e9:	01 d0                	add    %edx,%eax
  1007eb:	c1 e0 03             	shl    $0x3,%eax
  1007ee:	89 c2                	mov    %eax,%edx
  1007f0:	8b 45 f0             	mov    -0x10(%ebp),%eax
  1007f3:	01 d0                	add    %edx,%eax
  1007f5:	8b 40 0c             	mov    0xc(%eax),%eax
  1007f8:	89 45 e0             	mov    %eax,-0x20(%ebp)
  1007fb:	8b 55 f4             	mov    -0xc(%ebp),%edx
  1007fe:	89 d0                	mov    %edx,%eax
  100800:	c1 e0 02             	shl    $0x2,%eax
  100803:	01 d0                	add    %edx,%eax
  100805:	c1 e0 03             	shl    $0x3,%eax
  100808:	89 c2                	mov    %eax,%edx
  10080a:	8b 45 f0             	mov    -0x10(%ebp),%eax
  10080d:	01 d0                	add    %edx,%eax
  10080f:	8b 40 14             	mov    0x14(%eax),%eax
  100812:	89 45 e4             	mov    %eax,-0x1c(%ebp)
  100815:	c7 44 24 04 40 24 10 	movl   $0x102440,0x4(%esp)
  10081c:	00 
  10081d:	8b 45 e8             	mov    -0x18(%ebp),%eax
  100820:	89 04 24             	mov    %eax,(%esp)
  100823:	e8 63 02 00 00       	call   100a8b <strcmp>
  100828:	85 c0                	test   %eax,%eax
  10082a:	75 34                	jne    100860 <elf_form_multiboot+0xec>
  10082c:	8b 55 f4             	mov    -0xc(%ebp),%edx
  10082f:	89 d0                	mov    %edx,%eax
  100831:	c1 e0 02             	shl    $0x2,%eax
  100834:	01 d0                	add    %edx,%eax
  100836:	c1 e0 03             	shl    $0x3,%eax
  100839:	89 c2                	mov    %eax,%edx
  10083b:	8b 45 f0             	mov    -0x10(%ebp),%eax
  10083e:	01 d0                	add    %edx,%eax
  100840:	8b 40 0c             	mov    0xc(%eax),%eax
  100843:	89 45 d8             	mov    %eax,-0x28(%ebp)
  100846:	8b 55 f4             	mov    -0xc(%ebp),%edx
  100849:	89 d0                	mov    %edx,%eax
  10084b:	c1 e0 02             	shl    $0x2,%eax
  10084e:	01 d0                	add    %edx,%eax
  100850:	c1 e0 03             	shl    $0x3,%eax
  100853:	89 c2                	mov    %eax,%edx
  100855:	8b 45 f0             	mov    -0x10(%ebp),%eax
  100858:	01 d0                	add    %edx,%eax
  10085a:	8b 40 14             	mov    0x14(%eax),%eax
  10085d:	89 45 dc             	mov    %eax,-0x24(%ebp)
  100860:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100864:	8b 55 f4             	mov    -0xc(%ebp),%edx
  100867:	8b 45 0c             	mov    0xc(%ebp),%eax
  10086a:	8b 40 1c             	mov    0x1c(%eax),%eax
  10086d:	39 c2                	cmp    %eax,%edx
  10086f:	0f 82 37 ff ff ff    	jb     1007ac <elf_form_multiboot+0x38>
  100875:	8b 45 08             	mov    0x8(%ebp),%eax
  100878:	8b 55 d8             	mov    -0x28(%ebp),%edx
  10087b:	89 10                	mov    %edx,(%eax)
  10087d:	8b 55 dc             	mov    -0x24(%ebp),%edx
  100880:	89 50 04             	mov    %edx,0x4(%eax)
  100883:	8b 55 e0             	mov    -0x20(%ebp),%edx
  100886:	89 50 08             	mov    %edx,0x8(%eax)
  100889:	8b 55 e4             	mov    -0x1c(%ebp),%edx
  10088c:	89 50 0c             	mov    %edx,0xc(%eax)
  10088f:	8b 45 08             	mov    0x8(%ebp),%eax
  100892:	c9                   	leave  
  100893:	c2 04 00             	ret    $0x4

00100896 <elf_look_symbol>:
  100896:	55                   	push   %ebp
  100897:	89 e5                	mov    %esp,%ebp
  100899:	83 ec 10             	sub    $0x10,%esp
  10089c:	c7 45 fc 00 00 00 00 	movl   $0x0,-0x4(%ebp)
  1008a3:	eb 78                	jmp    10091d <elf_look_symbol+0x87>
  1008a5:	8b 45 0c             	mov    0xc(%ebp),%eax
  1008a8:	8b 00                	mov    (%eax),%eax
  1008aa:	8b 55 fc             	mov    -0x4(%ebp),%edx
  1008ad:	c1 e2 04             	shl    $0x4,%edx
  1008b0:	01 d0                	add    %edx,%eax
  1008b2:	0f b6 40 0c          	movzbl 0xc(%eax),%eax
  1008b6:	0f b6 c0             	movzbl %al,%eax
  1008b9:	83 e0 0f             	and    $0xf,%eax
  1008bc:	83 f8 02             	cmp    $0x2,%eax
  1008bf:	75 57                	jne    100918 <elf_look_symbol+0x82>
  1008c1:	8b 45 0c             	mov    0xc(%ebp),%eax
  1008c4:	8b 00                	mov    (%eax),%eax
  1008c6:	8b 55 fc             	mov    -0x4(%ebp),%edx
  1008c9:	c1 e2 04             	shl    $0x4,%edx
  1008cc:	01 d0                	add    %edx,%eax
  1008ce:	8b 40 04             	mov    0x4(%eax),%eax
  1008d1:	3b 45 08             	cmp    0x8(%ebp),%eax
  1008d4:	77 43                	ja     100919 <elf_look_symbol+0x83>
  1008d6:	8b 45 0c             	mov    0xc(%ebp),%eax
  1008d9:	8b 00                	mov    (%eax),%eax
  1008db:	8b 55 fc             	mov    -0x4(%ebp),%edx
  1008de:	c1 e2 04             	shl    $0x4,%edx
  1008e1:	01 d0                	add    %edx,%eax
  1008e3:	8b 50 04             	mov    0x4(%eax),%edx
  1008e6:	8b 45 0c             	mov    0xc(%ebp),%eax
  1008e9:	8b 00                	mov    (%eax),%eax
  1008eb:	8b 4d fc             	mov    -0x4(%ebp),%ecx
  1008ee:	c1 e1 04             	shl    $0x4,%ecx
  1008f1:	01 c8                	add    %ecx,%eax
  1008f3:	8b 40 08             	mov    0x8(%eax),%eax
  1008f6:	01 d0                	add    %edx,%eax
  1008f8:	3b 45 08             	cmp    0x8(%ebp),%eax
  1008fb:	76 1c                	jbe    100919 <elf_look_symbol+0x83>
  1008fd:	8b 45 0c             	mov    0xc(%ebp),%eax
  100900:	8b 40 08             	mov    0x8(%eax),%eax
  100903:	89 c2                	mov    %eax,%edx
  100905:	8b 45 0c             	mov    0xc(%ebp),%eax
  100908:	8b 00                	mov    (%eax),%eax
  10090a:	8b 4d fc             	mov    -0x4(%ebp),%ecx
  10090d:	c1 e1 04             	shl    $0x4,%ecx
  100910:	01 c8                	add    %ecx,%eax
  100912:	8b 00                	mov    (%eax),%eax
  100914:	01 d0                	add    %edx,%eax
  100916:	eb 1e                	jmp    100936 <elf_look_symbol+0xa0>
  100918:	90                   	nop
  100919:	83 45 fc 01          	addl   $0x1,-0x4(%ebp)
  10091d:	8b 55 fc             	mov    -0x4(%ebp),%edx
  100920:	8b 45 0c             	mov    0xc(%ebp),%eax
  100923:	8b 40 04             	mov    0x4(%eax),%eax
  100926:	c1 e8 04             	shr    $0x4,%eax
  100929:	39 c2                	cmp    %eax,%edx
  10092b:	0f 82 74 ff ff ff    	jb     1008a5 <elf_look_symbol+0xf>
  100931:	b8 00 00 00 00       	mov    $0x0,%eax
  100936:	c9                   	leave  
  100937:	c3                   	ret    

00100938 <memcpy>:
  100938:	55                   	push   %ebp
  100939:	89 e5                	mov    %esp,%ebp
  10093b:	83 ec 10             	sub    $0x10,%esp
  10093e:	8b 45 08             	mov    0x8(%ebp),%eax
  100941:	89 45 fc             	mov    %eax,-0x4(%ebp)
  100944:	8b 45 0c             	mov    0xc(%ebp),%eax
  100947:	89 45 f8             	mov    %eax,-0x8(%ebp)
  10094a:	c7 45 f4 00 00 00 00 	movl   $0x0,-0xc(%ebp)
  100951:	83 7d 0c 00          	cmpl   $0x0,0xc(%ebp)
  100955:	74 06                	je     10095d <memcpy+0x25>
  100957:	83 7d 08 00          	cmpl   $0x0,0x8(%ebp)
  10095b:	75 1e                	jne    10097b <memcpy+0x43>
  10095d:	8b 45 08             	mov    0x8(%ebp),%eax
  100960:	eb 25                	jmp    100987 <memcpy+0x4f>
  100962:	8b 45 f8             	mov    -0x8(%ebp),%eax
  100965:	0f b6 10             	movzbl (%eax),%edx
  100968:	8b 45 fc             	mov    -0x4(%ebp),%eax
  10096b:	88 10                	mov    %dl,(%eax)
  10096d:	83 45 fc 01          	addl   $0x1,-0x4(%ebp)
  100971:	83 45 f8 01          	addl   $0x1,-0x8(%ebp)
  100975:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100979:	eb 01                	jmp    10097c <memcpy+0x44>
  10097b:	90                   	nop
  10097c:	8b 45 f4             	mov    -0xc(%ebp),%eax
  10097f:	3b 45 10             	cmp    0x10(%ebp),%eax
  100982:	72 de                	jb     100962 <memcpy+0x2a>
  100984:	8b 45 08             	mov    0x8(%ebp),%eax
  100987:	c9                   	leave  
  100988:	c3                   	ret    

00100989 <memset>:
  100989:	55                   	push   %ebp
  10098a:	89 e5                	mov    %esp,%ebp
  10098c:	83 ec 14             	sub    $0x14,%esp
  10098f:	8b 45 0c             	mov    0xc(%ebp),%eax
  100992:	88 45 ec             	mov    %al,-0x14(%ebp)
  100995:	8b 45 08             	mov    0x8(%ebp),%eax
  100998:	89 45 f4             	mov    %eax,-0xc(%ebp)
  10099b:	c7 45 fc 00 00 00 00 	movl   $0x0,-0x4(%ebp)
  1009a2:	c7 45 f8 00 00 00 00 	movl   $0x0,-0x8(%ebp)
  1009a9:	83 7d 08 00          	cmpl   $0x0,0x8(%ebp)
  1009ad:	75 08                	jne    1009b7 <memset+0x2e>
  1009af:	eb 62                	jmp    100a13 <memset+0x8a>
  1009b1:	83 45 fc 01          	addl   $0x1,-0x4(%ebp)
  1009b5:	eb 01                	jmp    1009b8 <memset+0x2f>
  1009b7:	90                   	nop
  1009b8:	8b 45 f4             	mov    -0xc(%ebp),%eax
  1009bb:	0f b6 00             	movzbl (%eax),%eax
  1009be:	84 c0                	test   %al,%al
  1009c0:	75 ef                	jne    1009b1 <memset+0x28>
  1009c2:	8b 45 fc             	mov    -0x4(%ebp),%eax
  1009c5:	3b 45 10             	cmp    0x10(%ebp),%eax
  1009c8:	77 1d                	ja     1009e7 <memset+0x5e>
  1009ca:	eb 11                	jmp    1009dd <memset+0x54>
  1009cc:	8b 45 f4             	mov    -0xc(%ebp),%eax
  1009cf:	0f b6 55 ec          	movzbl -0x14(%ebp),%edx
  1009d3:	88 10                	mov    %dl,(%eax)
  1009d5:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  1009d9:	83 45 f8 01          	addl   $0x1,-0x8(%ebp)
  1009dd:	8b 45 f8             	mov    -0x8(%ebp),%eax
  1009e0:	3b 45 10             	cmp    0x10(%ebp),%eax
  1009e3:	72 e7                	jb     1009cc <memset+0x43>
  1009e5:	eb 22                	jmp    100a09 <memset+0x80>
  1009e7:	c7 45 f8 00 00 00 00 	movl   $0x0,-0x8(%ebp)
  1009ee:	eb 11                	jmp    100a01 <memset+0x78>
  1009f0:	8b 45 f4             	mov    -0xc(%ebp),%eax
  1009f3:	0f b6 55 ec          	movzbl -0x14(%ebp),%edx
  1009f7:	88 10                	mov    %dl,(%eax)
  1009f9:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  1009fd:	83 45 f8 01          	addl   $0x1,-0x8(%ebp)
  100a01:	8b 45 f8             	mov    -0x8(%ebp),%eax
  100a04:	3b 45 fc             	cmp    -0x4(%ebp),%eax
  100a07:	7c e7                	jl     1009f0 <memset+0x67>
  100a09:	8b 45 f4             	mov    -0xc(%ebp),%eax
  100a0c:	c6 00 00             	movb   $0x0,(%eax)
  100a0f:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100a13:	c9                   	leave  
  100a14:	c3                   	ret    

00100a15 <bzer>:
  100a15:	55                   	push   %ebp
  100a16:	89 e5                	mov    %esp,%ebp
  100a18:	83 ec 10             	sub    $0x10,%esp
  100a1b:	8b 45 08             	mov    0x8(%ebp),%eax
  100a1e:	89 45 f4             	mov    %eax,-0xc(%ebp)
  100a21:	c7 45 fc 00 00 00 00 	movl   $0x0,-0x4(%ebp)
  100a28:	c7 45 f8 00 00 00 00 	movl   $0x0,-0x8(%ebp)
  100a2f:	83 7d 08 00          	cmpl   $0x0,0x8(%ebp)
  100a33:	75 08                	jne    100a3d <bzer+0x28>
  100a35:	eb 52                	jmp    100a89 <bzer+0x74>
  100a37:	83 45 fc 01          	addl   $0x1,-0x4(%ebp)
  100a3b:	eb 01                	jmp    100a3e <bzer+0x29>
  100a3d:	90                   	nop
  100a3e:	8b 45 f4             	mov    -0xc(%ebp),%eax
  100a41:	0f b6 00             	movzbl (%eax),%eax
  100a44:	84 c0                	test   %al,%al
  100a46:	75 ef                	jne    100a37 <bzer+0x22>
  100a48:	8b 45 fc             	mov    -0x4(%ebp),%eax
  100a4b:	3b 45 0c             	cmp    0xc(%ebp),%eax
  100a4e:	72 1a                	jb     100a6a <bzer+0x55>
  100a50:	eb 0e                	jmp    100a60 <bzer+0x4b>
  100a52:	8b 45 f4             	mov    -0xc(%ebp),%eax
  100a55:	c6 00 00             	movb   $0x0,(%eax)
  100a58:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100a5c:	83 45 f8 01          	addl   $0x1,-0x8(%ebp)
  100a60:	8b 45 f8             	mov    -0x8(%ebp),%eax
  100a63:	3b 45 0c             	cmp    0xc(%ebp),%eax
  100a66:	72 ea                	jb     100a52 <bzer+0x3d>
  100a68:	eb 1f                	jmp    100a89 <bzer+0x74>
  100a6a:	c7 45 f8 00 00 00 00 	movl   $0x0,-0x8(%ebp)
  100a71:	eb 0e                	jmp    100a81 <bzer+0x6c>
  100a73:	8b 45 f4             	mov    -0xc(%ebp),%eax
  100a76:	c6 00 00             	movb   $0x0,(%eax)
  100a79:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100a7d:	83 45 f8 01          	addl   $0x1,-0x8(%ebp)
  100a81:	8b 45 f8             	mov    -0x8(%ebp),%eax
  100a84:	3b 45 fc             	cmp    -0x4(%ebp),%eax
  100a87:	7c ea                	jl     100a73 <bzer+0x5e>
  100a89:	c9                   	leave  
  100a8a:	c3                   	ret    

00100a8b <strcmp>:
  100a8b:	55                   	push   %ebp
  100a8c:	89 e5                	mov    %esp,%ebp
  100a8e:	83 ec 10             	sub    $0x10,%esp
  100a91:	8b 45 08             	mov    0x8(%ebp),%eax
  100a94:	89 45 fc             	mov    %eax,-0x4(%ebp)
  100a97:	8b 45 0c             	mov    0xc(%ebp),%eax
  100a9a:	89 45 f8             	mov    %eax,-0x8(%ebp)
  100a9d:	8b 45 fc             	mov    -0x4(%ebp),%eax
  100aa0:	0f b6 00             	movzbl (%eax),%eax
  100aa3:	88 45 f7             	mov    %al,-0x9(%ebp)
  100aa6:	83 45 fc 01          	addl   $0x1,-0x4(%ebp)
  100aaa:	8b 45 f8             	mov    -0x8(%ebp),%eax
  100aad:	0f b6 00             	movzbl (%eax),%eax
  100ab0:	88 45 f6             	mov    %al,-0xa(%ebp)
  100ab3:	83 45 f8 01          	addl   $0x1,-0x8(%ebp)
  100ab7:	80 7d f7 00          	cmpb   $0x0,-0x9(%ebp)
  100abb:	75 10                	jne    100acd <strcmp+0x42>
  100abd:	0f be 55 f7          	movsbl -0x9(%ebp),%edx
  100ac1:	0f be 45 f6          	movsbl -0xa(%ebp),%eax
  100ac5:	89 d1                	mov    %edx,%ecx
  100ac7:	29 c1                	sub    %eax,%ecx
  100ac9:	89 c8                	mov    %ecx,%eax
  100acb:	eb 17                	jmp    100ae4 <strcmp+0x59>
  100acd:	0f b6 45 f7          	movzbl -0x9(%ebp),%eax
  100ad1:	3a 45 f6             	cmp    -0xa(%ebp),%al
  100ad4:	74 c7                	je     100a9d <strcmp+0x12>
  100ad6:	0f be 55 f7          	movsbl -0x9(%ebp),%edx
  100ada:	0f be 45 f6          	movsbl -0xa(%ebp),%eax
  100ade:	89 d1                	mov    %edx,%ecx
  100ae0:	29 c1                	sub    %eax,%ecx
  100ae2:	89 c8                	mov    %ecx,%eax
  100ae4:	c9                   	leave  
  100ae5:	c3                   	ret    

00100ae6 <strcpy>:
  100ae6:	55                   	push   %ebp
  100ae7:	89 e5                	mov    %esp,%ebp
  100ae9:	83 ec 10             	sub    $0x10,%esp
  100aec:	8b 45 08             	mov    0x8(%ebp),%eax
  100aef:	89 45 fc             	mov    %eax,-0x4(%ebp)
  100af2:	8b 45 0c             	mov    0xc(%ebp),%eax
  100af5:	89 45 f8             	mov    %eax,-0x8(%ebp)
  100af8:	83 7d 08 00          	cmpl   $0x0,0x8(%ebp)
  100afc:	74 06                	je     100b04 <strcpy+0x1e>
  100afe:	83 7d 0c 00          	cmpl   $0x0,0xc(%ebp)
  100b02:	75 05                	jne    100b09 <strcpy+0x23>
  100b04:	8b 45 08             	mov    0x8(%ebp),%eax
  100b07:	eb 25                	jmp    100b2e <strcpy+0x48>
  100b09:	8b 45 f8             	mov    -0x8(%ebp),%eax
  100b0c:	0f b6 10             	movzbl (%eax),%edx
  100b0f:	8b 45 fc             	mov    -0x4(%ebp),%eax
  100b12:	88 10                	mov    %dl,(%eax)
  100b14:	83 45 fc 01          	addl   $0x1,-0x4(%ebp)
  100b18:	8b 45 f8             	mov    -0x8(%ebp),%eax
  100b1b:	0f b6 00             	movzbl (%eax),%eax
  100b1e:	84 c0                	test   %al,%al
  100b20:	0f 95 c0             	setne  %al
  100b23:	83 45 f8 01          	addl   $0x1,-0x8(%ebp)
  100b27:	84 c0                	test   %al,%al
  100b29:	75 de                	jne    100b09 <strcpy+0x23>
  100b2b:	8b 45 08             	mov    0x8(%ebp),%eax
  100b2e:	c9                   	leave  
  100b2f:	c3                   	ret    

00100b30 <strcat>:
  100b30:	55                   	push   %ebp
  100b31:	89 e5                	mov    %esp,%ebp
  100b33:	83 ec 10             	sub    $0x10,%esp
  100b36:	8b 45 0c             	mov    0xc(%ebp),%eax
  100b39:	89 45 fc             	mov    %eax,-0x4(%ebp)
  100b3c:	8b 45 08             	mov    0x8(%ebp),%eax
  100b3f:	89 45 f8             	mov    %eax,-0x8(%ebp)
  100b42:	83 7d 08 00          	cmpl   $0x0,0x8(%ebp)
  100b46:	74 06                	je     100b4e <strcat+0x1e>
  100b48:	83 7d 0c 00          	cmpl   $0x0,0xc(%ebp)
  100b4c:	75 07                	jne    100b55 <strcat+0x25>
  100b4e:	b8 00 00 00 00       	mov    $0x0,%eax
  100b53:	eb 3b                	jmp    100b90 <strcat+0x60>
  100b55:	90                   	nop
  100b56:	8b 45 f8             	mov    -0x8(%ebp),%eax
  100b59:	0f b6 00             	movzbl (%eax),%eax
  100b5c:	84 c0                	test   %al,%al
  100b5e:	0f 95 c0             	setne  %al
  100b61:	83 45 f8 01          	addl   $0x1,-0x8(%ebp)
  100b65:	84 c0                	test   %al,%al
  100b67:	75 ed                	jne    100b56 <strcat+0x26>
  100b69:	eb 0f                	jmp    100b7a <strcat+0x4a>
  100b6b:	8b 45 fc             	mov    -0x4(%ebp),%eax
  100b6e:	0f b6 10             	movzbl (%eax),%edx
  100b71:	8b 45 f8             	mov    -0x8(%ebp),%eax
  100b74:	88 10                	mov    %dl,(%eax)
  100b76:	83 45 f8 01          	addl   $0x1,-0x8(%ebp)
  100b7a:	8b 45 fc             	mov    -0x4(%ebp),%eax
  100b7d:	0f b6 00             	movzbl (%eax),%eax
  100b80:	84 c0                	test   %al,%al
  100b82:	0f 95 c0             	setne  %al
  100b85:	83 45 fc 01          	addl   $0x1,-0x4(%ebp)
  100b89:	84 c0                	test   %al,%al
  100b8b:	75 de                	jne    100b6b <strcat+0x3b>
  100b8d:	8b 45 08             	mov    0x8(%ebp),%eax
  100b90:	c9                   	leave  
  100b91:	c3                   	ret    

00100b92 <strlen>:
  100b92:	55                   	push   %ebp
  100b93:	89 e5                	mov    %esp,%ebp
  100b95:	83 ec 10             	sub    $0x10,%esp
  100b98:	c7 45 fc 00 00 00 00 	movl   $0x0,-0x4(%ebp)
  100b9f:	eb 04                	jmp    100ba5 <strlen+0x13>
  100ba1:	83 45 fc 01          	addl   $0x1,-0x4(%ebp)
  100ba5:	8b 45 08             	mov    0x8(%ebp),%eax
  100ba8:	0f b6 00             	movzbl (%eax),%eax
  100bab:	84 c0                	test   %al,%al
  100bad:	0f 95 c0             	setne  %al
  100bb0:	83 45 08 01          	addl   $0x1,0x8(%ebp)
  100bb4:	84 c0                	test   %al,%al
  100bb6:	75 e9                	jne    100ba1 <strlen+0xf>
  100bb8:	8b 45 fc             	mov    -0x4(%ebp),%eax
  100bbb:	c9                   	leave  
  100bbc:	c3                   	ret    
  100bbd:	66 90                	xchg   %ax,%ax
  100bbf:	90                   	nop

00100bc0 <move_point>:
  100bc0:	55                   	push   %ebp
  100bc1:	89 e5                	mov    %esp,%ebp
  100bc3:	83 ec 28             	sub    $0x28,%esp
  100bc6:	0f b7 05 04 b0 10 00 	movzwl 0x10b004,%eax
  100bcd:	89 c2                	mov    %eax,%edx
  100bcf:	89 d0                	mov    %edx,%eax
  100bd1:	c1 e0 02             	shl    $0x2,%eax
  100bd4:	01 d0                	add    %edx,%eax
  100bd6:	c1 e0 04             	shl    $0x4,%eax
  100bd9:	89 c2                	mov    %eax,%edx
  100bdb:	0f b7 05 06 b0 10 00 	movzwl 0x10b006,%eax
  100be2:	01 d0                	add    %edx,%eax
  100be4:	66 89 45 f6          	mov    %ax,-0xa(%ebp)
  100be8:	c7 44 24 04 0e 00 00 	movl   $0xe,0x4(%esp)
  100bef:	00 
  100bf0:	c7 04 24 d4 03 00 00 	movl   $0x3d4,(%esp)
  100bf7:	e8 c8 01 00 00       	call   100dc4 <outb>
  100bfc:	0f b7 45 f6          	movzwl -0xa(%ebp),%eax
  100c00:	66 c1 e8 08          	shr    $0x8,%ax
  100c04:	0f b7 c0             	movzwl %ax,%eax
  100c07:	89 44 24 04          	mov    %eax,0x4(%esp)
  100c0b:	c7 04 24 d5 03 00 00 	movl   $0x3d5,(%esp)
  100c12:	e8 ad 01 00 00       	call   100dc4 <outb>
  100c17:	c7 44 24 04 0f 00 00 	movl   $0xf,0x4(%esp)
  100c1e:	00 
  100c1f:	c7 04 24 d4 03 00 00 	movl   $0x3d4,(%esp)
  100c26:	e8 99 01 00 00       	call   100dc4 <outb>
  100c2b:	0f b7 45 f6          	movzwl -0xa(%ebp),%eax
  100c2f:	89 44 24 04          	mov    %eax,0x4(%esp)
  100c33:	c7 04 24 d5 03 00 00 	movl   $0x3d5,(%esp)
  100c3a:	e8 85 01 00 00       	call   100dc4 <outb>
  100c3f:	c9                   	leave  
  100c40:	c3                   	ret    

00100c41 <screen_clear>:
  100c41:	55                   	push   %ebp
  100c42:	89 e5                	mov    %esp,%ebp
  100c44:	83 ec 18             	sub    $0x18,%esp
  100c47:	66 c7 45 f2 20 07    	movw   $0x720,-0xe(%ebp)
  100c4d:	c7 45 f4 00 00 00 00 	movl   $0x0,-0xc(%ebp)
  100c54:	c7 45 f4 00 00 00 00 	movl   $0x0,-0xc(%ebp)
  100c5b:	eb 17                	jmp    100c74 <screen_clear+0x33>
  100c5d:	a1 1c 24 10 00       	mov    0x10241c,%eax
  100c62:	8b 55 f4             	mov    -0xc(%ebp),%edx
  100c65:	01 d2                	add    %edx,%edx
  100c67:	01 c2                	add    %eax,%edx
  100c69:	0f b7 45 f2          	movzwl -0xe(%ebp),%eax
  100c6d:	66 89 02             	mov    %ax,(%edx)
  100c70:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100c74:	81 7d f4 cf 07 00 00 	cmpl   $0x7cf,-0xc(%ebp)
  100c7b:	7e e0                	jle    100c5d <screen_clear+0x1c>
  100c7d:	66 c7 05 04 b0 10 00 	movw   $0x0,0x10b004
  100c84:	00 00 
  100c86:	66 c7 05 06 b0 10 00 	movw   $0x0,0x10b006
  100c8d:	00 00 
  100c8f:	e8 2c ff ff ff       	call   100bc0 <move_point>
  100c94:	c9                   	leave  
  100c95:	c3                   	ret    

00100c96 <screen_char>:
  100c96:	55                   	push   %ebp
  100c97:	89 e5                	mov    %esp,%ebp
  100c99:	83 ec 28             	sub    $0x28,%esp
  100c9c:	8b 45 08             	mov    0x8(%ebp),%eax
  100c9f:	88 45 e4             	mov    %al,-0x1c(%ebp)
  100ca2:	8b 45 0c             	mov    0xc(%ebp),%eax
  100ca5:	89 c2                	mov    %eax,%edx
  100ca7:	8b 45 10             	mov    0x10(%ebp),%eax
  100caa:	09 d0                	or     %edx,%eax
  100cac:	89 c2                	mov    %eax,%edx
  100cae:	c1 e2 08             	shl    $0x8,%edx
  100cb1:	66 0f be 45 e4       	movsbw -0x1c(%ebp),%ax
  100cb6:	09 d0                	or     %edx,%eax
  100cb8:	66 89 45 f6          	mov    %ax,-0xa(%ebp)
  100cbc:	80 7d e4 0a          	cmpb   $0xa,-0x1c(%ebp)
  100cc0:	75 1b                	jne    100cdd <screen_char+0x47>
  100cc2:	0f b7 05 04 b0 10 00 	movzwl 0x10b004,%eax
  100cc9:	83 c0 01             	add    $0x1,%eax
  100ccc:	66 a3 04 b0 10 00    	mov    %ax,0x10b004
  100cd2:	66 c7 05 06 b0 10 00 	movw   $0x0,0x10b006
  100cd9:	00 00 
  100cdb:	eb 72                	jmp    100d4f <screen_char+0xb9>
  100cdd:	80 7d e4 09          	cmpb   $0x9,-0x1c(%ebp)
  100ce1:	75 12                	jne    100cf5 <screen_char+0x5f>
  100ce3:	0f b7 05 06 b0 10 00 	movzwl 0x10b006,%eax
  100cea:	83 c0 08             	add    $0x8,%eax
  100ced:	66 a3 06 b0 10 00    	mov    %ax,0x10b006
  100cf3:	eb 5a                	jmp    100d4f <screen_char+0xb9>
  100cf5:	80 7d e4 20          	cmpb   $0x20,-0x1c(%ebp)
  100cf9:	75 12                	jne    100d0d <screen_char+0x77>
  100cfb:	0f b7 05 06 b0 10 00 	movzwl 0x10b006,%eax
  100d02:	83 c0 01             	add    $0x1,%eax
  100d05:	66 a3 06 b0 10 00    	mov    %ax,0x10b006
  100d0b:	eb 42                	jmp    100d4f <screen_char+0xb9>
  100d0d:	8b 0d 1c 24 10 00    	mov    0x10241c,%ecx
  100d13:	0f b7 05 04 b0 10 00 	movzwl 0x10b004,%eax
  100d1a:	0f bf d0             	movswl %ax,%edx
  100d1d:	89 d0                	mov    %edx,%eax
  100d1f:	c1 e0 02             	shl    $0x2,%eax
  100d22:	01 d0                	add    %edx,%eax
  100d24:	c1 e0 04             	shl    $0x4,%eax
  100d27:	89 c2                	mov    %eax,%edx
  100d29:	0f b7 05 06 b0 10 00 	movzwl 0x10b006,%eax
  100d30:	98                   	cwtl   
  100d31:	01 d0                	add    %edx,%eax
  100d33:	01 c0                	add    %eax,%eax
  100d35:	8d 14 01             	lea    (%ecx,%eax,1),%edx
  100d38:	0f b7 45 f6          	movzwl -0xa(%ebp),%eax
  100d3c:	66 89 02             	mov    %ax,(%edx)
  100d3f:	0f b7 05 06 b0 10 00 	movzwl 0x10b006,%eax
  100d46:	83 c0 01             	add    $0x1,%eax
  100d49:	66 a3 06 b0 10 00    	mov    %ax,0x10b006
  100d4f:	0f b7 05 06 b0 10 00 	movzwl 0x10b006,%eax
  100d56:	66 83 f8 50          	cmp    $0x50,%ax
  100d5a:	7e 19                	jle    100d75 <screen_char+0xdf>
  100d5c:	0f b7 05 04 b0 10 00 	movzwl 0x10b004,%eax
  100d63:	83 c0 01             	add    $0x1,%eax
  100d66:	66 a3 04 b0 10 00    	mov    %ax,0x10b004
  100d6c:	66 c7 05 06 b0 10 00 	movw   $0x0,0x10b006
  100d73:	00 00 
  100d75:	e8 46 fe ff ff       	call   100bc0 <move_point>
  100d7a:	c9                   	leave  
  100d7b:	c3                   	ret    

00100d7c <screen_string>:
  100d7c:	55                   	push   %ebp
  100d7d:	89 e5                	mov    %esp,%ebp
  100d7f:	83 ec 28             	sub    $0x28,%esp
  100d82:	c7 45 f4 00 00 00 00 	movl   $0x0,-0xc(%ebp)
  100d89:	eb 28                	jmp    100db3 <screen_string+0x37>
  100d8b:	8b 55 f4             	mov    -0xc(%ebp),%edx
  100d8e:	8b 45 08             	mov    0x8(%ebp),%eax
  100d91:	01 d0                	add    %edx,%eax
  100d93:	0f b6 00             	movzbl (%eax),%eax
  100d96:	0f be c0             	movsbl %al,%eax
  100d99:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100d9d:	8b 55 10             	mov    0x10(%ebp),%edx
  100da0:	89 54 24 08          	mov    %edx,0x8(%esp)
  100da4:	8b 55 0c             	mov    0xc(%ebp),%edx
  100da7:	89 54 24 04          	mov    %edx,0x4(%esp)
  100dab:	89 04 24             	mov    %eax,(%esp)
  100dae:	e8 e3 fe ff ff       	call   100c96 <screen_char>
  100db3:	8b 55 f4             	mov    -0xc(%ebp),%edx
  100db6:	8b 45 08             	mov    0x8(%ebp),%eax
  100db9:	01 d0                	add    %edx,%eax
  100dbb:	0f b6 00             	movzbl (%eax),%eax
  100dbe:	84 c0                	test   %al,%al
  100dc0:	75 c9                	jne    100d8b <screen_string+0xf>
  100dc2:	c9                   	leave  
  100dc3:	c3                   	ret    

00100dc4 <outb>:
  100dc4:	55                   	push   %ebp
  100dc5:	89 e5                	mov    %esp,%ebp
  100dc7:	83 ec 08             	sub    $0x8,%esp
  100dca:	8b 55 08             	mov    0x8(%ebp),%edx
  100dcd:	8b 45 0c             	mov    0xc(%ebp),%eax
  100dd0:	66 89 55 fc          	mov    %dx,-0x4(%ebp)
  100dd4:	88 45 f8             	mov    %al,-0x8(%ebp)
  100dd7:	0f b7 55 fc          	movzwl -0x4(%ebp),%edx
  100ddb:	0f b6 45 f8          	movzbl -0x8(%ebp),%eax
  100ddf:	ee                   	out    %al,(%dx)
  100de0:	c9                   	leave  
  100de1:	c3                   	ret    

00100de2 <inb>:
  100de2:	55                   	push   %ebp
  100de3:	89 e5                	mov    %esp,%ebp
  100de5:	53                   	push   %ebx
  100de6:	83 ec 14             	sub    $0x14,%esp
  100de9:	8b 45 08             	mov    0x8(%ebp),%eax
  100dec:	66 89 45 e8          	mov    %ax,-0x18(%ebp)
  100df0:	0f b7 55 e8          	movzwl -0x18(%ebp),%edx
  100df4:	66 89 55 ea          	mov    %dx,-0x16(%ebp)
  100df8:	0f b7 55 ea          	movzwl -0x16(%ebp),%edx
  100dfc:	ec                   	in     (%dx),%al
  100dfd:	89 c3                	mov    %eax,%ebx
  100dff:	88 5d fb             	mov    %bl,-0x5(%ebp)
  100e02:	0f b6 45 fb          	movzbl -0x5(%ebp),%eax
  100e06:	83 c4 14             	add    $0x14,%esp
  100e09:	5b                   	pop    %ebx
  100e0a:	5d                   	pop    %ebp
  100e0b:	c3                   	ret    

00100e0c <inw>:
  100e0c:	55                   	push   %ebp
  100e0d:	89 e5                	mov    %esp,%ebp
  100e0f:	53                   	push   %ebx
  100e10:	83 ec 14             	sub    $0x14,%esp
  100e13:	8b 45 08             	mov    0x8(%ebp),%eax
  100e16:	66 89 45 e8          	mov    %ax,-0x18(%ebp)
  100e1a:	0f b7 55 e8          	movzwl -0x18(%ebp),%edx
  100e1e:	66 89 55 ea          	mov    %dx,-0x16(%ebp)
  100e22:	0f b7 55 ea          	movzwl -0x16(%ebp),%edx
  100e26:	66 ed                	in     (%dx),%ax
  100e28:	89 c3                	mov    %eax,%ebx
  100e2a:	66 89 5d fa          	mov    %bx,-0x6(%ebp)
  100e2e:	0f b7 45 fa          	movzwl -0x6(%ebp),%eax
  100e32:	83 c4 14             	add    $0x14,%esp
  100e35:	5b                   	pop    %ebx
  100e36:	5d                   	pop    %ebp
  100e37:	c3                   	ret    

00100e38 <prints>:
  100e38:	55                   	push   %ebp
  100e39:	89 e5                	mov    %esp,%ebp
  100e3b:	83 ec 18             	sub    $0x18,%esp
  100e3e:	c7 44 24 08 04 00 00 	movl   $0x4,0x8(%esp)
  100e45:	00 
  100e46:	c7 44 24 04 00 00 00 	movl   $0x0,0x4(%esp)
  100e4d:	00 
  100e4e:	8b 45 08             	mov    0x8(%ebp),%eax
  100e51:	89 04 24             	mov    %eax,(%esp)
  100e54:	e8 23 ff ff ff       	call   100d7c <screen_string>
  100e59:	c9                   	leave  
  100e5a:	c3                   	ret    

00100e5b <printchar>:
  100e5b:	55                   	push   %ebp
  100e5c:	89 e5                	mov    %esp,%ebp
  100e5e:	83 ec 28             	sub    $0x28,%esp
  100e61:	8b 45 08             	mov    0x8(%ebp),%eax
  100e64:	88 45 f4             	mov    %al,-0xc(%ebp)
  100e67:	0f be 45 f4          	movsbl -0xc(%ebp),%eax
  100e6b:	c7 44 24 08 04 00 00 	movl   $0x4,0x8(%esp)
  100e72:	00 
  100e73:	c7 44 24 04 00 00 00 	movl   $0x0,0x4(%esp)
  100e7a:	00 
  100e7b:	89 04 24             	mov    %eax,(%esp)
  100e7e:	e8 13 fe ff ff       	call   100c96 <screen_char>
  100e83:	c9                   	leave  
  100e84:	c3                   	ret    

00100e85 <printi>:
  100e85:	55                   	push   %ebp
  100e86:	89 e5                	mov    %esp,%ebp
  100e88:	83 ec 48             	sub    $0x48,%esp
  100e8b:	c7 45 f4 00 00 00 00 	movl   $0x0,-0xc(%ebp)
  100e92:	8b 45 08             	mov    0x8(%ebp),%eax
  100e95:	89 45 f0             	mov    %eax,-0x10(%ebp)
  100e98:	83 7d f0 00          	cmpl   $0x0,-0x10(%ebp)
  100e9c:	79 03                	jns    100ea1 <printi+0x1c>
  100e9e:	f7 5d 08             	negl   0x8(%ebp)
  100ea1:	8b 4d 08             	mov    0x8(%ebp),%ecx
  100ea4:	ba 67 66 66 66       	mov    $0x66666667,%edx
  100ea9:	89 c8                	mov    %ecx,%eax
  100eab:	f7 ea                	imul   %edx
  100ead:	c1 fa 02             	sar    $0x2,%edx
  100eb0:	89 c8                	mov    %ecx,%eax
  100eb2:	c1 f8 1f             	sar    $0x1f,%eax
  100eb5:	29 c2                	sub    %eax,%edx
  100eb7:	89 d0                	mov    %edx,%eax
  100eb9:	c1 e0 02             	shl    $0x2,%eax
  100ebc:	01 d0                	add    %edx,%eax
  100ebe:	01 c0                	add    %eax,%eax
  100ec0:	89 ca                	mov    %ecx,%edx
  100ec2:	29 c2                	sub    %eax,%edx
  100ec4:	89 d0                	mov    %edx,%eax
  100ec6:	83 c0 30             	add    $0x30,%eax
  100ec9:	8d 4d d0             	lea    -0x30(%ebp),%ecx
  100ecc:	8b 55 f4             	mov    -0xc(%ebp),%edx
  100ecf:	01 ca                	add    %ecx,%edx
  100ed1:	88 02                	mov    %al,(%edx)
  100ed3:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100ed7:	8b 4d 08             	mov    0x8(%ebp),%ecx
  100eda:	ba 67 66 66 66       	mov    $0x66666667,%edx
  100edf:	89 c8                	mov    %ecx,%eax
  100ee1:	f7 ea                	imul   %edx
  100ee3:	c1 fa 02             	sar    $0x2,%edx
  100ee6:	89 c8                	mov    %ecx,%eax
  100ee8:	c1 f8 1f             	sar    $0x1f,%eax
  100eeb:	89 d1                	mov    %edx,%ecx
  100eed:	29 c1                	sub    %eax,%ecx
  100eef:	89 c8                	mov    %ecx,%eax
  100ef1:	89 45 08             	mov    %eax,0x8(%ebp)
  100ef4:	83 7d 08 00          	cmpl   $0x0,0x8(%ebp)
  100ef8:	7f a7                	jg     100ea1 <printi+0x1c>
  100efa:	83 7d f0 00          	cmpl   $0x0,-0x10(%ebp)
  100efe:	79 0f                	jns    100f0f <printi+0x8a>
  100f00:	8d 55 d0             	lea    -0x30(%ebp),%edx
  100f03:	8b 45 f4             	mov    -0xc(%ebp),%eax
  100f06:	01 d0                	add    %edx,%eax
  100f08:	c6 00 2d             	movb   $0x2d,(%eax)
  100f0b:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100f0f:	83 6d f4 01          	subl   $0x1,-0xc(%ebp)
  100f13:	eb 2a                	jmp    100f3f <printi+0xba>
  100f15:	8d 55 d0             	lea    -0x30(%ebp),%edx
  100f18:	8b 45 f4             	mov    -0xc(%ebp),%eax
  100f1b:	01 d0                	add    %edx,%eax
  100f1d:	0f b6 00             	movzbl (%eax),%eax
  100f20:	0f be c0             	movsbl %al,%eax
  100f23:	c7 44 24 08 04 00 00 	movl   $0x4,0x8(%esp)
  100f2a:	00 
  100f2b:	c7 44 24 04 00 00 00 	movl   $0x0,0x4(%esp)
  100f32:	00 
  100f33:	89 04 24             	mov    %eax,(%esp)
  100f36:	e8 5b fd ff ff       	call   100c96 <screen_char>
  100f3b:	83 6d f4 01          	subl   $0x1,-0xc(%ebp)
  100f3f:	83 7d f4 00          	cmpl   $0x0,-0xc(%ebp)
  100f43:	79 d0                	jns    100f15 <printi+0x90>
  100f45:	c9                   	leave  
  100f46:	c3                   	ret    

00100f47 <printk>:
  100f47:	55                   	push   %ebp
  100f48:	89 e5                	mov    %esp,%ebp
  100f4a:	83 ec 28             	sub    $0x28,%esp
  100f4d:	8d 45 0c             	lea    0xc(%ebp),%eax
  100f50:	89 45 f4             	mov    %eax,-0xc(%ebp)
  100f53:	8b 45 08             	mov    0x8(%ebp),%eax
  100f56:	8b 55 f4             	mov    -0xc(%ebp),%edx
  100f59:	89 54 24 04          	mov    %edx,0x4(%esp)
  100f5d:	89 04 24             	mov    %eax,(%esp)
  100f60:	e8 0f 00 00 00       	call   100f74 <vprintk>
  100f65:	89 45 f0             	mov    %eax,-0x10(%ebp)
  100f68:	c7 45 f4 00 00 00 00 	movl   $0x0,-0xc(%ebp)
  100f6f:	8b 45 f0             	mov    -0x10(%ebp),%eax
  100f72:	c9                   	leave  
  100f73:	c3                   	ret    

00100f74 <vprintk>:
  100f74:	55                   	push   %ebp
  100f75:	89 e5                	mov    %esp,%ebp
  100f77:	83 ec 28             	sub    $0x28,%esp
  100f7a:	c7 45 f4 00 00 00 00 	movl   $0x0,-0xc(%ebp)
  100f81:	e9 b1 00 00 00       	jmp    101037 <vprintk+0xc3>
  100f86:	8b 45 08             	mov    0x8(%ebp),%eax
  100f89:	0f b6 00             	movzbl (%eax),%eax
  100f8c:	3c 25                	cmp    $0x25,%al
  100f8e:	0f 85 8a 00 00 00    	jne    10101e <vprintk+0xaa>
  100f94:	83 45 08 01          	addl   $0x1,0x8(%ebp)
  100f98:	8b 45 08             	mov    0x8(%ebp),%eax
  100f9b:	0f b6 00             	movzbl (%eax),%eax
  100f9e:	3c 63                	cmp    $0x63,%al
  100fa0:	75 1d                	jne    100fbf <vprintk+0x4b>
  100fa2:	83 45 0c 04          	addl   $0x4,0xc(%ebp)
  100fa6:	8b 45 0c             	mov    0xc(%ebp),%eax
  100fa9:	83 e8 04             	sub    $0x4,%eax
  100fac:	8b 00                	mov    (%eax),%eax
  100fae:	0f be c0             	movsbl %al,%eax
  100fb1:	89 04 24             	mov    %eax,(%esp)
  100fb4:	e8 a2 fe ff ff       	call   100e5b <printchar>
  100fb9:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100fbd:	eb 74                	jmp    101033 <vprintk+0xbf>
  100fbf:	8b 45 08             	mov    0x8(%ebp),%eax
  100fc2:	0f b6 00             	movzbl (%eax),%eax
  100fc5:	3c 64                	cmp    $0x64,%al
  100fc7:	75 1a                	jne    100fe3 <vprintk+0x6f>
  100fc9:	83 45 0c 04          	addl   $0x4,0xc(%ebp)
  100fcd:	8b 45 0c             	mov    0xc(%ebp),%eax
  100fd0:	83 e8 04             	sub    $0x4,%eax
  100fd3:	8b 00                	mov    (%eax),%eax
  100fd5:	89 04 24             	mov    %eax,(%esp)
  100fd8:	e8 a8 fe ff ff       	call   100e85 <printi>
  100fdd:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  100fe1:	eb 50                	jmp    101033 <vprintk+0xbf>
  100fe3:	8b 45 08             	mov    0x8(%ebp),%eax
  100fe6:	0f b6 00             	movzbl (%eax),%eax
  100fe9:	3c 73                	cmp    $0x73,%al
  100feb:	75 1a                	jne    101007 <vprintk+0x93>
  100fed:	83 45 0c 04          	addl   $0x4,0xc(%ebp)
  100ff1:	8b 45 0c             	mov    0xc(%ebp),%eax
  100ff4:	83 e8 04             	sub    $0x4,%eax
  100ff7:	8b 00                	mov    (%eax),%eax
  100ff9:	89 04 24             	mov    %eax,(%esp)
  100ffc:	e8 37 fe ff ff       	call   100e38 <prints>
  101001:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  101005:	eb 2c                	jmp    101033 <vprintk+0xbf>
  101007:	8b 45 08             	mov    0x8(%ebp),%eax
  10100a:	0f b6 00             	movzbl (%eax),%eax
  10100d:	0f be c0             	movsbl %al,%eax
  101010:	89 04 24             	mov    %eax,(%esp)
  101013:	e8 43 fe ff ff       	call   100e5b <printchar>
  101018:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  10101c:	eb 15                	jmp    101033 <vprintk+0xbf>
  10101e:	8b 45 08             	mov    0x8(%ebp),%eax
  101021:	0f b6 00             	movzbl (%eax),%eax
  101024:	0f be c0             	movsbl %al,%eax
  101027:	89 04 24             	mov    %eax,(%esp)
  10102a:	e8 2c fe ff ff       	call   100e5b <printchar>
  10102f:	83 45 f4 01          	addl   $0x1,-0xc(%ebp)
  101033:	83 45 08 01          	addl   $0x1,0x8(%ebp)
  101037:	8b 45 08             	mov    0x8(%ebp),%eax
  10103a:	0f b6 00             	movzbl (%eax),%eax
  10103d:	84 c0                	test   %al,%al
  10103f:	0f 85 41 ff ff ff    	jne    100f86 <vprintk+0x12>
  101045:	8b 45 f4             	mov    -0xc(%ebp),%eax
  101048:	c9                   	leave  
  101049:	c3                   	ret    
  10104a:	66 90                	xchg   %ax,%ax

0010104c <init_debug>:
  10104c:	55                   	push   %ebp
  10104d:	89 e5                	mov    %esp,%ebp
  10104f:	83 ec 28             	sub    $0x28,%esp
  101052:	8b 15 00 b0 10 00    	mov    0x10b000,%edx
  101058:	8d 45 e8             	lea    -0x18(%ebp),%eax
  10105b:	89 54 24 04          	mov    %edx,0x4(%esp)
  10105f:	89 04 24             	mov    %eax,(%esp)
  101062:	e8 0d f7 ff ff       	call   100774 <elf_form_multiboot>
  101067:	83 ec 04             	sub    $0x4,%esp
  10106a:	8b 45 e8             	mov    -0x18(%ebp),%eax
  10106d:	a3 08 b0 10 00       	mov    %eax,0x10b008
  101072:	8b 45 ec             	mov    -0x14(%ebp),%eax
  101075:	a3 0c b0 10 00       	mov    %eax,0x10b00c
  10107a:	8b 45 f0             	mov    -0x10(%ebp),%eax
  10107d:	a3 10 b0 10 00       	mov    %eax,0x10b010
  101082:	8b 45 f4             	mov    -0xc(%ebp),%eax
  101085:	a3 14 b0 10 00       	mov    %eax,0x10b014
  10108a:	c9                   	leave  
  10108b:	c3                   	ret    

0010108c <print_cur_status>:
  10108c:	55                   	push   %ebp
  10108d:	89 e5                	mov    %esp,%ebp
  10108f:	83 ec 28             	sub    $0x28,%esp
  101092:	8c 4d f6             	mov    %cs,-0xa(%ebp)
  101095:	8c 5d f4             	mov    %ds,-0xc(%ebp)
  101098:	8c 45 f2             	mov    %es,-0xe(%ebp)
  10109b:	8c 55 f0             	mov    %ss,-0x10(%ebp)
  10109e:	0f b7 45 f6          	movzwl -0xa(%ebp),%eax
  1010a2:	0f b7 c0             	movzwl %ax,%eax
  1010a5:	89 c2                	mov    %eax,%edx
  1010a7:	83 e2 03             	and    $0x3,%edx
  1010aa:	a1 18 b0 10 00       	mov    0x10b018,%eax
  1010af:	89 54 24 08          	mov    %edx,0x8(%esp)
  1010b3:	89 44 24 04          	mov    %eax,0x4(%esp)
  1010b7:	c7 04 24 48 24 10 00 	movl   $0x102448,(%esp)
  1010be:	e8 84 fe ff ff       	call   100f47 <printk>
  1010c3:	0f b7 45 f6          	movzwl -0xa(%ebp),%eax
  1010c7:	0f b7 d0             	movzwl %ax,%edx
  1010ca:	a1 18 b0 10 00       	mov    0x10b018,%eax
  1010cf:	89 54 24 08          	mov    %edx,0x8(%esp)
  1010d3:	89 44 24 04          	mov    %eax,0x4(%esp)
  1010d7:	c7 04 24 55 24 10 00 	movl   $0x102455,(%esp)
  1010de:	e8 64 fe ff ff       	call   100f47 <printk>
  1010e3:	0f b7 45 f4          	movzwl -0xc(%ebp),%eax
  1010e7:	0f b7 d0             	movzwl %ax,%edx
  1010ea:	a1 18 b0 10 00       	mov    0x10b018,%eax
  1010ef:	89 54 24 08          	mov    %edx,0x8(%esp)
  1010f3:	89 44 24 04          	mov    %eax,0x4(%esp)
  1010f7:	c7 04 24 62 24 10 00 	movl   $0x102462,(%esp)
  1010fe:	e8 44 fe ff ff       	call   100f47 <printk>
  101103:	0f b7 45 f2          	movzwl -0xe(%ebp),%eax
  101107:	0f b7 d0             	movzwl %ax,%edx
  10110a:	a1 18 b0 10 00       	mov    0x10b018,%eax
  10110f:	89 54 24 08          	mov    %edx,0x8(%esp)
  101113:	89 44 24 04          	mov    %eax,0x4(%esp)
  101117:	c7 04 24 6f 24 10 00 	movl   $0x10246f,(%esp)
  10111e:	e8 24 fe ff ff       	call   100f47 <printk>
  101123:	0f b7 45 f0          	movzwl -0x10(%ebp),%eax
  101127:	0f b7 d0             	movzwl %ax,%edx
  10112a:	a1 18 b0 10 00       	mov    0x10b018,%eax
  10112f:	89 54 24 08          	mov    %edx,0x8(%esp)
  101133:	89 44 24 04          	mov    %eax,0x4(%esp)
  101137:	c7 04 24 7c 24 10 00 	movl   $0x10247c,(%esp)
  10113e:	e8 04 fe ff ff       	call   100f47 <printk>
  101143:	c9                   	leave  
  101144:	c3                   	ret    

00101145 <panic>:
  101145:	55                   	push   %ebp
  101146:	89 e5                	mov    %esp,%ebp
  101148:	83 ec 18             	sub    $0x18,%esp
  10114b:	8b 45 08             	mov    0x8(%ebp),%eax
  10114e:	89 44 24 04          	mov    %eax,0x4(%esp)
  101152:	c7 04 24 89 24 10 00 	movl   $0x102489,(%esp)
  101159:	e8 e9 fd ff ff       	call   100f47 <printk>
  10115e:	e8 0e 00 00 00       	call   101171 <print_stack_trace>
  101163:	c7 04 24 a1 24 10 00 	movl   $0x1024a1,(%esp)
  10116a:	e8 d8 fd ff ff       	call   100f47 <printk>
  10116f:	eb fe                	jmp    10116f <panic+0x2a>

00101171 <print_stack_trace>:
  101171:	55                   	push   %ebp
  101172:	89 e5                	mov    %esp,%ebp
  101174:	53                   	push   %ebx
  101175:	83 ec 24             	sub    $0x24,%esp
  101178:	89 eb                	mov    %ebp,%ebx
  10117a:	89 5d f4             	mov    %ebx,-0xc(%ebp)
  10117d:	eb 3f                	jmp    1011be <print_stack_trace+0x4d>
  10117f:	8b 45 f4             	mov    -0xc(%ebp),%eax
  101182:	83 c0 04             	add    $0x4,%eax
  101185:	89 45 f0             	mov    %eax,-0x10(%ebp)
  101188:	8b 45 f0             	mov    -0x10(%ebp),%eax
  10118b:	8b 00                	mov    (%eax),%eax
  10118d:	c7 44 24 04 08 b0 10 	movl   $0x10b008,0x4(%esp)
  101194:	00 
  101195:	89 04 24             	mov    %eax,(%esp)
  101198:	e8 f9 f6 ff ff       	call   100896 <elf_look_symbol>
  10119d:	8b 55 f0             	mov    -0x10(%ebp),%edx
  1011a0:	8b 12                	mov    (%edx),%edx
  1011a2:	89 44 24 08          	mov    %eax,0x8(%esp)
  1011a6:	89 54 24 04          	mov    %edx,0x4(%esp)
  1011aa:	c7 04 24 a7 24 10 00 	movl   $0x1024a7,(%esp)
  1011b1:	e8 91 fd ff ff       	call   100f47 <printk>
  1011b6:	8b 45 f4             	mov    -0xc(%ebp),%eax
  1011b9:	8b 00                	mov    (%eax),%eax
  1011bb:	89 45 f4             	mov    %eax,-0xc(%ebp)
  1011be:	83 7d f4 00          	cmpl   $0x0,-0xc(%ebp)
  1011c2:	75 bb                	jne    10117f <print_stack_trace+0xe>
  1011c4:	83 c4 24             	add    $0x24,%esp
  1011c7:	5b                   	pop    %ebx
  1011c8:	5d                   	pop    %ebp
  1011c9:	c3                   	ret    
  1011ca:	66 90                	xchg   %ax,%ax

001011cc <init_gdt>:
  1011cc:	55                   	push   %ebp
  1011cd:	89 e5                	mov    %esp,%ebp
  1011cf:	83 ec 28             	sub    $0x28,%esp
  1011d2:	66 c7 05 48 cc 10 00 	movw   $0x27,0x10cc48
  1011d9:	27 00 
  1011db:	b8 20 cc 10 00       	mov    $0x10cc20,%eax
  1011e0:	a3 4a cc 10 00       	mov    %eax,0x10cc4a
  1011e5:	c7 44 24 10 00 00 00 	movl   $0x0,0x10(%esp)
  1011ec:	00 
  1011ed:	c7 44 24 0c 00 00 00 	movl   $0x0,0xc(%esp)
  1011f4:	00 
  1011f5:	c7 44 24 08 00 00 00 	movl   $0x0,0x8(%esp)
  1011fc:	00 
  1011fd:	c7 44 24 04 00 00 00 	movl   $0x0,0x4(%esp)
  101204:	00 
  101205:	c7 04 24 00 00 00 00 	movl   $0x0,(%esp)
  10120c:	e8 bf 00 00 00       	call   1012d0 <gdt_set_gate>
  101211:	c7 44 24 10 cf 00 00 	movl   $0xcf,0x10(%esp)
  101218:	00 
  101219:	c7 44 24 0c 9a 00 00 	movl   $0x9a,0xc(%esp)
  101220:	00 
  101221:	c7 44 24 08 ff ff ff 	movl   $0xffffffff,0x8(%esp)
  101228:	ff 
  101229:	c7 44 24 04 00 00 00 	movl   $0x0,0x4(%esp)
  101230:	00 
  101231:	c7 04 24 01 00 00 00 	movl   $0x1,(%esp)
  101238:	e8 93 00 00 00       	call   1012d0 <gdt_set_gate>
  10123d:	c7 44 24 10 cf 00 00 	movl   $0xcf,0x10(%esp)
  101244:	00 
  101245:	c7 44 24 0c 92 00 00 	movl   $0x92,0xc(%esp)
  10124c:	00 
  10124d:	c7 44 24 08 ff ff ff 	movl   $0xffffffff,0x8(%esp)
  101254:	ff 
  101255:	c7 44 24 04 00 00 00 	movl   $0x0,0x4(%esp)
  10125c:	00 
  10125d:	c7 04 24 02 00 00 00 	movl   $0x2,(%esp)
  101264:	e8 67 00 00 00       	call   1012d0 <gdt_set_gate>
  101269:	c7 44 24 10 cf 00 00 	movl   $0xcf,0x10(%esp)
  101270:	00 
  101271:	c7 44 24 0c fa 00 00 	movl   $0xfa,0xc(%esp)
  101278:	00 
  101279:	c7 44 24 08 ff ff ff 	movl   $0xffffffff,0x8(%esp)
  101280:	ff 
  101281:	c7 44 24 04 00 00 00 	movl   $0x0,0x4(%esp)
  101288:	00 
  101289:	c7 04 24 03 00 00 00 	movl   $0x3,(%esp)
  101290:	e8 3b 00 00 00       	call   1012d0 <gdt_set_gate>
  101295:	c7 44 24 10 cf 00 00 	movl   $0xcf,0x10(%esp)
  10129c:	00 
  10129d:	c7 44 24 0c f2 00 00 	movl   $0xf2,0xc(%esp)
  1012a4:	00 
  1012a5:	c7 44 24 08 ff ff ff 	movl   $0xffffffff,0x8(%esp)
  1012ac:	ff 
  1012ad:	c7 44 24 04 00 00 00 	movl   $0x0,0x4(%esp)
  1012b4:	00 
  1012b5:	c7 04 24 04 00 00 00 	movl   $0x4,(%esp)
  1012bc:	e8 0f 00 00 00       	call   1012d0 <gdt_set_gate>
  1012c1:	b8 48 cc 10 00       	mov    $0x10cc48,%eax
  1012c6:	89 04 24             	mov    %eax,(%esp)
  1012c9:	e8 a2 ee ff ff       	call   100170 <gdt_flush>
  1012ce:	c9                   	leave  
  1012cf:	c3                   	ret    

001012d0 <gdt_set_gate>:
  1012d0:	55                   	push   %ebp
  1012d1:	89 e5                	mov    %esp,%ebp
  1012d3:	83 ec 08             	sub    $0x8,%esp
  1012d6:	8b 55 14             	mov    0x14(%ebp),%edx
  1012d9:	8b 45 18             	mov    0x18(%ebp),%eax
  1012dc:	88 55 fc             	mov    %dl,-0x4(%ebp)
  1012df:	88 45 f8             	mov    %al,-0x8(%ebp)
  1012e2:	8b 45 0c             	mov    0xc(%ebp),%eax
  1012e5:	89 c2                	mov    %eax,%edx
  1012e7:	8b 45 08             	mov    0x8(%ebp),%eax
  1012ea:	66 89 14 c5 22 cc 10 	mov    %dx,0x10cc22(,%eax,8)
  1012f1:	00 
  1012f2:	8b 45 0c             	mov    0xc(%ebp),%eax
  1012f5:	c1 e8 10             	shr    $0x10,%eax
  1012f8:	89 c2                	mov    %eax,%edx
  1012fa:	8b 45 08             	mov    0x8(%ebp),%eax
  1012fd:	88 14 c5 24 cc 10 00 	mov    %dl,0x10cc24(,%eax,8)
  101304:	8b 45 0c             	mov    0xc(%ebp),%eax
  101307:	c1 e8 18             	shr    $0x18,%eax
  10130a:	89 c2                	mov    %eax,%edx
  10130c:	8b 45 08             	mov    0x8(%ebp),%eax
  10130f:	88 14 c5 27 cc 10 00 	mov    %dl,0x10cc27(,%eax,8)
  101316:	8b 45 10             	mov    0x10(%ebp),%eax
  101319:	89 c2                	mov    %eax,%edx
  10131b:	8b 45 08             	mov    0x8(%ebp),%eax
  10131e:	66 89 14 c5 20 cc 10 	mov    %dx,0x10cc20(,%eax,8)
  101325:	00 
  101326:	8b 45 10             	mov    0x10(%ebp),%eax
  101329:	c1 e8 10             	shr    $0x10,%eax
  10132c:	89 c2                	mov    %eax,%edx
  10132e:	83 e2 0f             	and    $0xf,%edx
  101331:	8b 45 08             	mov    0x8(%ebp),%eax
  101334:	88 14 c5 26 cc 10 00 	mov    %dl,0x10cc26(,%eax,8)
  10133b:	8b 45 08             	mov    0x8(%ebp),%eax
  10133e:	0f b6 04 c5 26 cc 10 	movzbl 0x10cc26(,%eax,8),%eax
  101345:	00 
  101346:	0f b6 55 f8          	movzbl -0x8(%ebp),%edx
  10134a:	83 e2 f0             	and    $0xfffffff0,%edx
  10134d:	09 d0                	or     %edx,%eax
  10134f:	89 c2                	mov    %eax,%edx
  101351:	8b 45 08             	mov    0x8(%ebp),%eax
  101354:	88 14 c5 26 cc 10 00 	mov    %dl,0x10cc26(,%eax,8)
  10135b:	8b 45 08             	mov    0x8(%ebp),%eax
  10135e:	0f b6 55 fc          	movzbl -0x4(%ebp),%edx
  101362:	88 14 c5 25 cc 10 00 	mov    %dl,0x10cc25(,%eax,8)
  101369:	c9                   	leave  
  10136a:	c3                   	ret    
  10136b:	90                   	nop

0010136c <entry>:
  10136c:	55                   	push   %ebp
  10136d:	89 e5                	mov    %esp,%ebp
  10136f:	83 ec 28             	sub    $0x28,%esp
  101372:	e8 d5 fc ff ff       	call   10104c <init_debug>
  101377:	e8 50 fe ff ff       	call   1011cc <init_gdt>
  10137c:	e8 0f ee ff ff       	call   100190 <init_idt>
  101381:	c7 45 f4 b7 24 10 00 	movl   $0x1024b7,-0xc(%ebp)
  101388:	e8 b4 f8 ff ff       	call   100c41 <screen_clear>
  10138d:	8b 45 f4             	mov    -0xc(%ebp),%eax
  101390:	89 44 24 04          	mov    %eax,0x4(%esp)
  101394:	c7 04 24 c4 24 10 00 	movl   $0x1024c4,(%esp)
  10139b:	e8 a7 fb ff ff       	call   100f47 <printk>
  1013a0:	cd 00                	int    $0x0
  1013a2:	cd 00                	int    $0x0
  1013a4:	eb fe                	jmp    1013a4 <entry+0x38>
  1013a6:	66 90                	xchg   %ax,%ax
  1013a8:	66 90                	xchg   %ax,%ax
  1013aa:	66 90                	xchg   %ax,%ax
  1013ac:	66 90                	xchg   %ax,%ax
  1013ae:	66 90                	xchg   %ax,%ax
  1013b0:	66 90                	xchg   %ax,%ax
  1013b2:	66 90                	xchg   %ax,%ax
  1013b4:	66 90                	xchg   %ax,%ax
  1013b6:	66 90                	xchg   %ax,%ax
  1013b8:	66 90                	xchg   %ax,%ax
  1013ba:	66 90                	xchg   %ax,%ax
  1013bc:	66 90                	xchg   %ax,%ax
  1013be:	66 90                	xchg   %ax,%ax
  1013c0:	66 90                	xchg   %ax,%ax
  1013c2:	66 90                	xchg   %ax,%ax
  1013c4:	66 90                	xchg   %ax,%ax
  1013c6:	66 90                	xchg   %ax,%ax
  1013c8:	66 90                	xchg   %ax,%ax
  1013ca:	66 90                	xchg   %ax,%ax
  1013cc:	66 90                	xchg   %ax,%ax
  1013ce:	66 90                	xchg   %ax,%ax
  1013d0:	66 90                	xchg   %ax,%ax
  1013d2:	66 90                	xchg   %ax,%ax
  1013d4:	66 90                	xchg   %ax,%ax
  1013d6:	66 90                	xchg   %ax,%ax
  1013d8:	66 90                	xchg   %ax,%ax
  1013da:	66 90                	xchg   %ax,%ax
  1013dc:	66 90                	xchg   %ax,%ax
  1013de:	66 90                	xchg   %ax,%ax
  1013e0:	66 90                	xchg   %ax,%ax
  1013e2:	66 90                	xchg   %ax,%ax
  1013e4:	66 90                	xchg   %ax,%ax
  1013e6:	66 90                	xchg   %ax,%ax
  1013e8:	66 90                	xchg   %ax,%ax
  1013ea:	66 90                	xchg   %ax,%ax
  1013ec:	66 90                	xchg   %ax,%ax
  1013ee:	66 90                	xchg   %ax,%ax
  1013f0:	66 90                	xchg   %ax,%ax
  1013f2:	66 90                	xchg   %ax,%ax
  1013f4:	66 90                	xchg   %ax,%ax
  1013f6:	66 90                	xchg   %ax,%ax
  1013f8:	66 90                	xchg   %ax,%ax
  1013fa:	66 90                	xchg   %ax,%ax
  1013fc:	66 90                	xchg   %ax,%ax
  1013fe:	66 90                	xchg   %ax,%ax
  101400:	66 90                	xchg   %ax,%ax
  101402:	66 90                	xchg   %ax,%ax
  101404:	66 90                	xchg   %ax,%ax
  101406:	66 90                	xchg   %ax,%ax
  101408:	66 90                	xchg   %ax,%ax
  10140a:	66 90                	xchg   %ax,%ax
  10140c:	66 90                	xchg   %ax,%ax
  10140e:	66 90                	xchg   %ax,%ax
  101410:	66 90                	xchg   %ax,%ax
  101412:	66 90                	xchg   %ax,%ax
  101414:	66 90                	xchg   %ax,%ax
  101416:	66 90                	xchg   %ax,%ax
  101418:	66 90                	xchg   %ax,%ax
  10141a:	66 90                	xchg   %ax,%ax
  10141c:	66 90                	xchg   %ax,%ax
  10141e:	66 90                	xchg   %ax,%ax
  101420:	66 90                	xchg   %ax,%ax
  101422:	66 90                	xchg   %ax,%ax
  101424:	66 90                	xchg   %ax,%ax
  101426:	66 90                	xchg   %ax,%ax
  101428:	66 90                	xchg   %ax,%ax
  10142a:	66 90                	xchg   %ax,%ax
  10142c:	66 90                	xchg   %ax,%ax
  10142e:	66 90                	xchg   %ax,%ax
  101430:	66 90                	xchg   %ax,%ax
  101432:	66 90                	xchg   %ax,%ax
  101434:	66 90                	xchg   %ax,%ax
  101436:	66 90                	xchg   %ax,%ax
  101438:	66 90                	xchg   %ax,%ax
  10143a:	66 90                	xchg   %ax,%ax
  10143c:	66 90                	xchg   %ax,%ax
  10143e:	66 90                	xchg   %ax,%ax
  101440:	66 90                	xchg   %ax,%ax
  101442:	66 90                	xchg   %ax,%ax
  101444:	66 90                	xchg   %ax,%ax
  101446:	66 90                	xchg   %ax,%ax
  101448:	66 90                	xchg   %ax,%ax
  10144a:	66 90                	xchg   %ax,%ax
  10144c:	66 90                	xchg   %ax,%ax
  10144e:	66 90                	xchg   %ax,%ax
  101450:	66 90                	xchg   %ax,%ax
  101452:	66 90                	xchg   %ax,%ax
  101454:	66 90                	xchg   %ax,%ax
  101456:	66 90                	xchg   %ax,%ax
  101458:	66 90                	xchg   %ax,%ax
  10145a:	66 90                	xchg   %ax,%ax
  10145c:	66 90                	xchg   %ax,%ax
  10145e:	66 90                	xchg   %ax,%ax
  101460:	66 90                	xchg   %ax,%ax
  101462:	66 90                	xchg   %ax,%ax
  101464:	66 90                	xchg   %ax,%ax
  101466:	66 90                	xchg   %ax,%ax
  101468:	66 90                	xchg   %ax,%ax
  10146a:	66 90                	xchg   %ax,%ax
  10146c:	66 90                	xchg   %ax,%ax
  10146e:	66 90                	xchg   %ax,%ax
  101470:	66 90                	xchg   %ax,%ax
  101472:	66 90                	xchg   %ax,%ax
  101474:	66 90                	xchg   %ax,%ax
  101476:	66 90                	xchg   %ax,%ax
  101478:	66 90                	xchg   %ax,%ax
  10147a:	66 90                	xchg   %ax,%ax
  10147c:	66 90                	xchg   %ax,%ax
  10147e:	66 90                	xchg   %ax,%ax
  101480:	66 90                	xchg   %ax,%ax
  101482:	66 90                	xchg   %ax,%ax
  101484:	66 90                	xchg   %ax,%ax
  101486:	66 90                	xchg   %ax,%ax
  101488:	66 90                	xchg   %ax,%ax
  10148a:	66 90                	xchg   %ax,%ax
  10148c:	66 90                	xchg   %ax,%ax
  10148e:	66 90                	xchg   %ax,%ax
  101490:	66 90                	xchg   %ax,%ax
  101492:	66 90                	xchg   %ax,%ax
  101494:	66 90                	xchg   %ax,%ax
  101496:	66 90                	xchg   %ax,%ax
  101498:	66 90                	xchg   %ax,%ax
  10149a:	66 90                	xchg   %ax,%ax
  10149c:	66 90                	xchg   %ax,%ax
  10149e:	66 90                	xchg   %ax,%ax
  1014a0:	66 90                	xchg   %ax,%ax
  1014a2:	66 90                	xchg   %ax,%ax
  1014a4:	66 90                	xchg   %ax,%ax
  1014a6:	66 90                	xchg   %ax,%ax
  1014a8:	66 90                	xchg   %ax,%ax
  1014aa:	66 90                	xchg   %ax,%ax
  1014ac:	66 90                	xchg   %ax,%ax
  1014ae:	66 90                	xchg   %ax,%ax
  1014b0:	66 90                	xchg   %ax,%ax
  1014b2:	66 90                	xchg   %ax,%ax
  1014b4:	66 90                	xchg   %ax,%ax
  1014b6:	66 90                	xchg   %ax,%ax
  1014b8:	66 90                	xchg   %ax,%ax
  1014ba:	66 90                	xchg   %ax,%ax
  1014bc:	66 90                	xchg   %ax,%ax
  1014be:	66 90                	xchg   %ax,%ax
  1014c0:	66 90                	xchg   %ax,%ax
  1014c2:	66 90                	xchg   %ax,%ax
  1014c4:	66 90                	xchg   %ax,%ax
  1014c6:	66 90                	xchg   %ax,%ax
  1014c8:	66 90                	xchg   %ax,%ax
  1014ca:	66 90                	xchg   %ax,%ax
  1014cc:	66 90                	xchg   %ax,%ax
  1014ce:	66 90                	xchg   %ax,%ax
  1014d0:	66 90                	xchg   %ax,%ax
  1014d2:	66 90                	xchg   %ax,%ax
  1014d4:	66 90                	xchg   %ax,%ax
  1014d6:	66 90                	xchg   %ax,%ax
  1014d8:	66 90                	xchg   %ax,%ax
  1014da:	66 90                	xchg   %ax,%ax
  1014dc:	66 90                	xchg   %ax,%ax
  1014de:	66 90                	xchg   %ax,%ax
  1014e0:	66 90                	xchg   %ax,%ax
  1014e2:	66 90                	xchg   %ax,%ax
  1014e4:	66 90                	xchg   %ax,%ax
  1014e6:	66 90                	xchg   %ax,%ax
  1014e8:	66 90                	xchg   %ax,%ax
  1014ea:	66 90                	xchg   %ax,%ax
  1014ec:	66 90                	xchg   %ax,%ax
  1014ee:	66 90                	xchg   %ax,%ax
  1014f0:	66 90                	xchg   %ax,%ax
  1014f2:	66 90                	xchg   %ax,%ax
  1014f4:	66 90                	xchg   %ax,%ax
  1014f6:	66 90                	xchg   %ax,%ax
  1014f8:	66 90                	xchg   %ax,%ax
  1014fa:	66 90                	xchg   %ax,%ax
  1014fc:	66 90                	xchg   %ax,%ax
  1014fe:	66 90                	xchg   %ax,%ax
  101500:	66 90                	xchg   %ax,%ax
  101502:	66 90                	xchg   %ax,%ax
  101504:	66 90                	xchg   %ax,%ax
  101506:	66 90                	xchg   %ax,%ax
  101508:	66 90                	xchg   %ax,%ax
  10150a:	66 90                	xchg   %ax,%ax
  10150c:	66 90                	xchg   %ax,%ax
  10150e:	66 90                	xchg   %ax,%ax
  101510:	66 90                	xchg   %ax,%ax
  101512:	66 90                	xchg   %ax,%ax
  101514:	66 90                	xchg   %ax,%ax
  101516:	66 90                	xchg   %ax,%ax
  101518:	66 90                	xchg   %ax,%ax
  10151a:	66 90                	xchg   %ax,%ax
  10151c:	66 90                	xchg   %ax,%ax
  10151e:	66 90                	xchg   %ax,%ax
  101520:	66 90                	xchg   %ax,%ax
  101522:	66 90                	xchg   %ax,%ax
  101524:	66 90                	xchg   %ax,%ax
  101526:	66 90                	xchg   %ax,%ax
  101528:	66 90                	xchg   %ax,%ax
  10152a:	66 90                	xchg   %ax,%ax
  10152c:	66 90                	xchg   %ax,%ax
  10152e:	66 90                	xchg   %ax,%ax
  101530:	66 90                	xchg   %ax,%ax
  101532:	66 90                	xchg   %ax,%ax
  101534:	66 90                	xchg   %ax,%ax
  101536:	66 90                	xchg   %ax,%ax
  101538:	66 90                	xchg   %ax,%ax
  10153a:	66 90                	xchg   %ax,%ax
  10153c:	66 90                	xchg   %ax,%ax
  10153e:	66 90                	xchg   %ax,%ax
  101540:	66 90                	xchg   %ax,%ax
  101542:	66 90                	xchg   %ax,%ax
  101544:	66 90                	xchg   %ax,%ax
  101546:	66 90                	xchg   %ax,%ax
  101548:	66 90                	xchg   %ax,%ax
  10154a:	66 90                	xchg   %ax,%ax
  10154c:	66 90                	xchg   %ax,%ax
  10154e:	66 90                	xchg   %ax,%ax
  101550:	66 90                	xchg   %ax,%ax
  101552:	66 90                	xchg   %ax,%ax
  101554:	66 90                	xchg   %ax,%ax
  101556:	66 90                	xchg   %ax,%ax
  101558:	66 90                	xchg   %ax,%ax
  10155a:	66 90                	xchg   %ax,%ax
  10155c:	66 90                	xchg   %ax,%ax
  10155e:	66 90                	xchg   %ax,%ax
  101560:	66 90                	xchg   %ax,%ax
  101562:	66 90                	xchg   %ax,%ax
  101564:	66 90                	xchg   %ax,%ax
  101566:	66 90                	xchg   %ax,%ax
  101568:	66 90                	xchg   %ax,%ax
  10156a:	66 90                	xchg   %ax,%ax
  10156c:	66 90                	xchg   %ax,%ax
  10156e:	66 90                	xchg   %ax,%ax
  101570:	66 90                	xchg   %ax,%ax
  101572:	66 90                	xchg   %ax,%ax
  101574:	66 90                	xchg   %ax,%ax
  101576:	66 90                	xchg   %ax,%ax
  101578:	66 90                	xchg   %ax,%ax
  10157a:	66 90                	xchg   %ax,%ax
  10157c:	66 90                	xchg   %ax,%ax
  10157e:	66 90                	xchg   %ax,%ax
  101580:	66 90                	xchg   %ax,%ax
  101582:	66 90                	xchg   %ax,%ax
  101584:	66 90                	xchg   %ax,%ax
  101586:	66 90                	xchg   %ax,%ax
  101588:	66 90                	xchg   %ax,%ax
  10158a:	66 90                	xchg   %ax,%ax
  10158c:	66 90                	xchg   %ax,%ax
  10158e:	66 90                	xchg   %ax,%ax
  101590:	66 90                	xchg   %ax,%ax
  101592:	66 90                	xchg   %ax,%ax
  101594:	66 90                	xchg   %ax,%ax
  101596:	66 90                	xchg   %ax,%ax
  101598:	66 90                	xchg   %ax,%ax
  10159a:	66 90                	xchg   %ax,%ax
  10159c:	66 90                	xchg   %ax,%ax
  10159e:	66 90                	xchg   %ax,%ax
  1015a0:	66 90                	xchg   %ax,%ax
  1015a2:	66 90                	xchg   %ax,%ax
  1015a4:	66 90                	xchg   %ax,%ax
  1015a6:	66 90                	xchg   %ax,%ax
  1015a8:	66 90                	xchg   %ax,%ax
  1015aa:	66 90                	xchg   %ax,%ax
  1015ac:	66 90                	xchg   %ax,%ax
  1015ae:	66 90                	xchg   %ax,%ax
  1015b0:	66 90                	xchg   %ax,%ax
  1015b2:	66 90                	xchg   %ax,%ax
  1015b4:	66 90                	xchg   %ax,%ax
  1015b6:	66 90                	xchg   %ax,%ax
  1015b8:	66 90                	xchg   %ax,%ax
  1015ba:	66 90                	xchg   %ax,%ax
  1015bc:	66 90                	xchg   %ax,%ax
  1015be:	66 90                	xchg   %ax,%ax
  1015c0:	66 90                	xchg   %ax,%ax
  1015c2:	66 90                	xchg   %ax,%ax
  1015c4:	66 90                	xchg   %ax,%ax
  1015c6:	66 90                	xchg   %ax,%ax
  1015c8:	66 90                	xchg   %ax,%ax
  1015ca:	66 90                	xchg   %ax,%ax
  1015cc:	66 90                	xchg   %ax,%ax
  1015ce:	66 90                	xchg   %ax,%ax
  1015d0:	66 90                	xchg   %ax,%ax
  1015d2:	66 90                	xchg   %ax,%ax
  1015d4:	66 90                	xchg   %ax,%ax
  1015d6:	66 90                	xchg   %ax,%ax
  1015d8:	66 90                	xchg   %ax,%ax
  1015da:	66 90                	xchg   %ax,%ax
  1015dc:	66 90                	xchg   %ax,%ax
  1015de:	66 90                	xchg   %ax,%ax
  1015e0:	66 90                	xchg   %ax,%ax
  1015e2:	66 90                	xchg   %ax,%ax
  1015e4:	66 90                	xchg   %ax,%ax
  1015e6:	66 90                	xchg   %ax,%ax
  1015e8:	66 90                	xchg   %ax,%ax
  1015ea:	66 90                	xchg   %ax,%ax
  1015ec:	66 90                	xchg   %ax,%ax
  1015ee:	66 90                	xchg   %ax,%ax
  1015f0:	66 90                	xchg   %ax,%ax
  1015f2:	66 90                	xchg   %ax,%ax
  1015f4:	66 90                	xchg   %ax,%ax
  1015f6:	66 90                	xchg   %ax,%ax
  1015f8:	66 90                	xchg   %ax,%ax
  1015fa:	66 90                	xchg   %ax,%ax
  1015fc:	66 90                	xchg   %ax,%ax
  1015fe:	66 90                	xchg   %ax,%ax
  101600:	66 90                	xchg   %ax,%ax
  101602:	66 90                	xchg   %ax,%ax
  101604:	66 90                	xchg   %ax,%ax
  101606:	66 90                	xchg   %ax,%ax
  101608:	66 90                	xchg   %ax,%ax
  10160a:	66 90                	xchg   %ax,%ax
  10160c:	66 90                	xchg   %ax,%ax
  10160e:	66 90                	xchg   %ax,%ax
  101610:	66 90                	xchg   %ax,%ax
  101612:	66 90                	xchg   %ax,%ax
  101614:	66 90                	xchg   %ax,%ax
  101616:	66 90                	xchg   %ax,%ax
  101618:	66 90                	xchg   %ax,%ax
  10161a:	66 90                	xchg   %ax,%ax
  10161c:	66 90                	xchg   %ax,%ax
  10161e:	66 90                	xchg   %ax,%ax
  101620:	66 90                	xchg   %ax,%ax
  101622:	66 90                	xchg   %ax,%ax
  101624:	66 90                	xchg   %ax,%ax
  101626:	66 90                	xchg   %ax,%ax
  101628:	66 90                	xchg   %ax,%ax
  10162a:	66 90                	xchg   %ax,%ax
  10162c:	66 90                	xchg   %ax,%ax
  10162e:	66 90                	xchg   %ax,%ax
  101630:	66 90                	xchg   %ax,%ax
  101632:	66 90                	xchg   %ax,%ax
  101634:	66 90                	xchg   %ax,%ax
  101636:	66 90                	xchg   %ax,%ax
  101638:	66 90                	xchg   %ax,%ax
  10163a:	66 90                	xchg   %ax,%ax
  10163c:	66 90                	xchg   %ax,%ax
  10163e:	66 90                	xchg   %ax,%ax
  101640:	66 90                	xchg   %ax,%ax
  101642:	66 90                	xchg   %ax,%ax
  101644:	66 90                	xchg   %ax,%ax
  101646:	66 90                	xchg   %ax,%ax
  101648:	66 90                	xchg   %ax,%ax
  10164a:	66 90                	xchg   %ax,%ax
  10164c:	66 90                	xchg   %ax,%ax
  10164e:	66 90                	xchg   %ax,%ax
  101650:	66 90                	xchg   %ax,%ax
  101652:	66 90                	xchg   %ax,%ax
  101654:	66 90                	xchg   %ax,%ax
  101656:	66 90                	xchg   %ax,%ax
  101658:	66 90                	xchg   %ax,%ax
  10165a:	66 90                	xchg   %ax,%ax
  10165c:	66 90                	xchg   %ax,%ax
  10165e:	66 90                	xchg   %ax,%ax
  101660:	66 90                	xchg   %ax,%ax
  101662:	66 90                	xchg   %ax,%ax
  101664:	66 90                	xchg   %ax,%ax
  101666:	66 90                	xchg   %ax,%ax
  101668:	66 90                	xchg   %ax,%ax
  10166a:	66 90                	xchg   %ax,%ax
  10166c:	66 90                	xchg   %ax,%ax
  10166e:	66 90                	xchg   %ax,%ax
  101670:	66 90                	xchg   %ax,%ax
  101672:	66 90                	xchg   %ax,%ax
  101674:	66 90                	xchg   %ax,%ax
  101676:	66 90                	xchg   %ax,%ax
  101678:	66 90                	xchg   %ax,%ax
  10167a:	66 90                	xchg   %ax,%ax
  10167c:	66 90                	xchg   %ax,%ax
  10167e:	66 90                	xchg   %ax,%ax
  101680:	66 90                	xchg   %ax,%ax
  101682:	66 90                	xchg   %ax,%ax
  101684:	66 90                	xchg   %ax,%ax
  101686:	66 90                	xchg   %ax,%ax
  101688:	66 90                	xchg   %ax,%ax
  10168a:	66 90                	xchg   %ax,%ax
  10168c:	66 90                	xchg   %ax,%ax
  10168e:	66 90                	xchg   %ax,%ax
  101690:	66 90                	xchg   %ax,%ax
  101692:	66 90                	xchg   %ax,%ax
  101694:	66 90                	xchg   %ax,%ax
  101696:	66 90                	xchg   %ax,%ax
  101698:	66 90                	xchg   %ax,%ax
  10169a:	66 90                	xchg   %ax,%ax
  10169c:	66 90                	xchg   %ax,%ax
  10169e:	66 90                	xchg   %ax,%ax
  1016a0:	66 90                	xchg   %ax,%ax
  1016a2:	66 90                	xchg   %ax,%ax
  1016a4:	66 90                	xchg   %ax,%ax
  1016a6:	66 90                	xchg   %ax,%ax
  1016a8:	66 90                	xchg   %ax,%ax
  1016aa:	66 90                	xchg   %ax,%ax
  1016ac:	66 90                	xchg   %ax,%ax
  1016ae:	66 90                	xchg   %ax,%ax
  1016b0:	66 90                	xchg   %ax,%ax
  1016b2:	66 90                	xchg   %ax,%ax
  1016b4:	66 90                	xchg   %ax,%ax
  1016b6:	66 90                	xchg   %ax,%ax
  1016b8:	66 90                	xchg   %ax,%ax
  1016ba:	66 90                	xchg   %ax,%ax
  1016bc:	66 90                	xchg   %ax,%ax
  1016be:	66 90                	xchg   %ax,%ax
  1016c0:	66 90                	xchg   %ax,%ax
  1016c2:	66 90                	xchg   %ax,%ax
  1016c4:	66 90                	xchg   %ax,%ax
  1016c6:	66 90                	xchg   %ax,%ax
  1016c8:	66 90                	xchg   %ax,%ax
  1016ca:	66 90                	xchg   %ax,%ax
  1016cc:	66 90                	xchg   %ax,%ax
  1016ce:	66 90                	xchg   %ax,%ax
  1016d0:	66 90                	xchg   %ax,%ax
  1016d2:	66 90                	xchg   %ax,%ax
  1016d4:	66 90                	xchg   %ax,%ax
  1016d6:	66 90                	xchg   %ax,%ax
  1016d8:	66 90                	xchg   %ax,%ax
  1016da:	66 90                	xchg   %ax,%ax
  1016dc:	66 90                	xchg   %ax,%ax
  1016de:	66 90                	xchg   %ax,%ax
  1016e0:	66 90                	xchg   %ax,%ax
  1016e2:	66 90                	xchg   %ax,%ax
  1016e4:	66 90                	xchg   %ax,%ax
  1016e6:	66 90                	xchg   %ax,%ax
  1016e8:	66 90                	xchg   %ax,%ax
  1016ea:	66 90                	xchg   %ax,%ax
  1016ec:	66 90                	xchg   %ax,%ax
  1016ee:	66 90                	xchg   %ax,%ax
  1016f0:	66 90                	xchg   %ax,%ax
  1016f2:	66 90                	xchg   %ax,%ax
  1016f4:	66 90                	xchg   %ax,%ax
  1016f6:	66 90                	xchg   %ax,%ax
  1016f8:	66 90                	xchg   %ax,%ax
  1016fa:	66 90                	xchg   %ax,%ax
  1016fc:	66 90                	xchg   %ax,%ax
  1016fe:	66 90                	xchg   %ax,%ax
  101700:	66 90                	xchg   %ax,%ax
  101702:	66 90                	xchg   %ax,%ax
  101704:	66 90                	xchg   %ax,%ax
  101706:	66 90                	xchg   %ax,%ax
  101708:	66 90                	xchg   %ax,%ax
  10170a:	66 90                	xchg   %ax,%ax
  10170c:	66 90                	xchg   %ax,%ax
  10170e:	66 90                	xchg   %ax,%ax
  101710:	66 90                	xchg   %ax,%ax
  101712:	66 90                	xchg   %ax,%ax
  101714:	66 90                	xchg   %ax,%ax
  101716:	66 90                	xchg   %ax,%ax
  101718:	66 90                	xchg   %ax,%ax
  10171a:	66 90                	xchg   %ax,%ax
  10171c:	66 90                	xchg   %ax,%ax
  10171e:	66 90                	xchg   %ax,%ax
  101720:	66 90                	xchg   %ax,%ax
  101722:	66 90                	xchg   %ax,%ax
  101724:	66 90                	xchg   %ax,%ax
  101726:	66 90                	xchg   %ax,%ax
  101728:	66 90                	xchg   %ax,%ax
  10172a:	66 90                	xchg   %ax,%ax
  10172c:	66 90                	xchg   %ax,%ax
  10172e:	66 90                	xchg   %ax,%ax
  101730:	66 90                	xchg   %ax,%ax
  101732:	66 90                	xchg   %ax,%ax
  101734:	66 90                	xchg   %ax,%ax
  101736:	66 90                	xchg   %ax,%ax
  101738:	66 90                	xchg   %ax,%ax
  10173a:	66 90                	xchg   %ax,%ax
  10173c:	66 90                	xchg   %ax,%ax
  10173e:	66 90                	xchg   %ax,%ax
  101740:	66 90                	xchg   %ax,%ax
  101742:	66 90                	xchg   %ax,%ax
  101744:	66 90                	xchg   %ax,%ax
  101746:	66 90                	xchg   %ax,%ax
  101748:	66 90                	xchg   %ax,%ax
  10174a:	66 90                	xchg   %ax,%ax
  10174c:	66 90                	xchg   %ax,%ax
  10174e:	66 90                	xchg   %ax,%ax
  101750:	66 90                	xchg   %ax,%ax
  101752:	66 90                	xchg   %ax,%ax
  101754:	66 90                	xchg   %ax,%ax
  101756:	66 90                	xchg   %ax,%ax
  101758:	66 90                	xchg   %ax,%ax
  10175a:	66 90                	xchg   %ax,%ax
  10175c:	66 90                	xchg   %ax,%ax
  10175e:	66 90                	xchg   %ax,%ax
  101760:	66 90                	xchg   %ax,%ax
  101762:	66 90                	xchg   %ax,%ax
  101764:	66 90                	xchg   %ax,%ax
  101766:	66 90                	xchg   %ax,%ax
  101768:	66 90                	xchg   %ax,%ax
  10176a:	66 90                	xchg   %ax,%ax
  10176c:	66 90                	xchg   %ax,%ax
  10176e:	66 90                	xchg   %ax,%ax
  101770:	66 90                	xchg   %ax,%ax
  101772:	66 90                	xchg   %ax,%ax
  101774:	66 90                	xchg   %ax,%ax
  101776:	66 90                	xchg   %ax,%ax
  101778:	66 90                	xchg   %ax,%ax
  10177a:	66 90                	xchg   %ax,%ax
  10177c:	66 90                	xchg   %ax,%ax
  10177e:	66 90                	xchg   %ax,%ax
  101780:	66 90                	xchg   %ax,%ax
  101782:	66 90                	xchg   %ax,%ax
  101784:	66 90                	xchg   %ax,%ax
  101786:	66 90                	xchg   %ax,%ax
  101788:	66 90                	xchg   %ax,%ax
  10178a:	66 90                	xchg   %ax,%ax
  10178c:	66 90                	xchg   %ax,%ax
  10178e:	66 90                	xchg   %ax,%ax
  101790:	66 90                	xchg   %ax,%ax
  101792:	66 90                	xchg   %ax,%ax
  101794:	66 90                	xchg   %ax,%ax
  101796:	66 90                	xchg   %ax,%ax
  101798:	66 90                	xchg   %ax,%ax
  10179a:	66 90                	xchg   %ax,%ax
  10179c:	66 90                	xchg   %ax,%ax
  10179e:	66 90                	xchg   %ax,%ax
  1017a0:	66 90                	xchg   %ax,%ax
  1017a2:	66 90                	xchg   %ax,%ax
  1017a4:	66 90                	xchg   %ax,%ax
  1017a6:	66 90                	xchg   %ax,%ax
  1017a8:	66 90                	xchg   %ax,%ax
  1017aa:	66 90                	xchg   %ax,%ax
  1017ac:	66 90                	xchg   %ax,%ax
  1017ae:	66 90                	xchg   %ax,%ax
  1017b0:	66 90                	xchg   %ax,%ax
  1017b2:	66 90                	xchg   %ax,%ax
  1017b4:	66 90                	xchg   %ax,%ax
  1017b6:	66 90                	xchg   %ax,%ax
  1017b8:	66 90                	xchg   %ax,%ax
  1017ba:	66 90                	xchg   %ax,%ax
  1017bc:	66 90                	xchg   %ax,%ax
  1017be:	66 90                	xchg   %ax,%ax
  1017c0:	66 90                	xchg   %ax,%ax
  1017c2:	66 90                	xchg   %ax,%ax
  1017c4:	66 90                	xchg   %ax,%ax
  1017c6:	66 90                	xchg   %ax,%ax
  1017c8:	66 90                	xchg   %ax,%ax
  1017ca:	66 90                	xchg   %ax,%ax
  1017cc:	66 90                	xchg   %ax,%ax
  1017ce:	66 90                	xchg   %ax,%ax
  1017d0:	66 90                	xchg   %ax,%ax
  1017d2:	66 90                	xchg   %ax,%ax
  1017d4:	66 90                	xchg   %ax,%ax
  1017d6:	66 90                	xchg   %ax,%ax
  1017d8:	66 90                	xchg   %ax,%ax
  1017da:	66 90                	xchg   %ax,%ax
  1017dc:	66 90                	xchg   %ax,%ax
  1017de:	66 90                	xchg   %ax,%ax
  1017e0:	66 90                	xchg   %ax,%ax
  1017e2:	66 90                	xchg   %ax,%ax
  1017e4:	66 90                	xchg   %ax,%ax
  1017e6:	66 90                	xchg   %ax,%ax
  1017e8:	66 90                	xchg   %ax,%ax
  1017ea:	66 90                	xchg   %ax,%ax
  1017ec:	66 90                	xchg   %ax,%ax
  1017ee:	66 90                	xchg   %ax,%ax
  1017f0:	66 90                	xchg   %ax,%ax
  1017f2:	66 90                	xchg   %ax,%ax
  1017f4:	66 90                	xchg   %ax,%ax
  1017f6:	66 90                	xchg   %ax,%ax
  1017f8:	66 90                	xchg   %ax,%ax
  1017fa:	66 90                	xchg   %ax,%ax
  1017fc:	66 90                	xchg   %ax,%ax
  1017fe:	66 90                	xchg   %ax,%ax
  101800:	66 90                	xchg   %ax,%ax
  101802:	66 90                	xchg   %ax,%ax
  101804:	66 90                	xchg   %ax,%ax
  101806:	66 90                	xchg   %ax,%ax
  101808:	66 90                	xchg   %ax,%ax
  10180a:	66 90                	xchg   %ax,%ax
  10180c:	66 90                	xchg   %ax,%ax
  10180e:	66 90                	xchg   %ax,%ax
  101810:	66 90                	xchg   %ax,%ax
  101812:	66 90                	xchg   %ax,%ax
  101814:	66 90                	xchg   %ax,%ax
  101816:	66 90                	xchg   %ax,%ax
  101818:	66 90                	xchg   %ax,%ax
  10181a:	66 90                	xchg   %ax,%ax
  10181c:	66 90                	xchg   %ax,%ax
  10181e:	66 90                	xchg   %ax,%ax
  101820:	66 90                	xchg   %ax,%ax
  101822:	66 90                	xchg   %ax,%ax
  101824:	66 90                	xchg   %ax,%ax
  101826:	66 90                	xchg   %ax,%ax
  101828:	66 90                	xchg   %ax,%ax
  10182a:	66 90                	xchg   %ax,%ax
  10182c:	66 90                	xchg   %ax,%ax
  10182e:	66 90                	xchg   %ax,%ax
  101830:	66 90                	xchg   %ax,%ax
  101832:	66 90                	xchg   %ax,%ax
  101834:	66 90                	xchg   %ax,%ax
  101836:	66 90                	xchg   %ax,%ax
  101838:	66 90                	xchg   %ax,%ax
  10183a:	66 90                	xchg   %ax,%ax
  10183c:	66 90                	xchg   %ax,%ax
  10183e:	66 90                	xchg   %ax,%ax
  101840:	66 90                	xchg   %ax,%ax
  101842:	66 90                	xchg   %ax,%ax
  101844:	66 90                	xchg   %ax,%ax
  101846:	66 90                	xchg   %ax,%ax
  101848:	66 90                	xchg   %ax,%ax
  10184a:	66 90                	xchg   %ax,%ax
  10184c:	66 90                	xchg   %ax,%ax
  10184e:	66 90                	xchg   %ax,%ax
  101850:	66 90                	xchg   %ax,%ax
  101852:	66 90                	xchg   %ax,%ax
  101854:	66 90                	xchg   %ax,%ax
  101856:	66 90                	xchg   %ax,%ax
  101858:	66 90                	xchg   %ax,%ax
  10185a:	66 90                	xchg   %ax,%ax
  10185c:	66 90                	xchg   %ax,%ax
  10185e:	66 90                	xchg   %ax,%ax
  101860:	66 90                	xchg   %ax,%ax
  101862:	66 90                	xchg   %ax,%ax
  101864:	66 90                	xchg   %ax,%ax
  101866:	66 90                	xchg   %ax,%ax
  101868:	66 90                	xchg   %ax,%ax
  10186a:	66 90                	xchg   %ax,%ax
  10186c:	66 90                	xchg   %ax,%ax
  10186e:	66 90                	xchg   %ax,%ax
  101870:	66 90                	xchg   %ax,%ax
  101872:	66 90                	xchg   %ax,%ax
  101874:	66 90                	xchg   %ax,%ax
  101876:	66 90                	xchg   %ax,%ax
  101878:	66 90                	xchg   %ax,%ax
  10187a:	66 90                	xchg   %ax,%ax
  10187c:	66 90                	xchg   %ax,%ax
  10187e:	66 90                	xchg   %ax,%ax
  101880:	66 90                	xchg   %ax,%ax
  101882:	66 90                	xchg   %ax,%ax
  101884:	66 90                	xchg   %ax,%ax
  101886:	66 90                	xchg   %ax,%ax
  101888:	66 90                	xchg   %ax,%ax
  10188a:	66 90                	xchg   %ax,%ax
  10188c:	66 90                	xchg   %ax,%ax
  10188e:	66 90                	xchg   %ax,%ax
  101890:	66 90                	xchg   %ax,%ax
  101892:	66 90                	xchg   %ax,%ax
  101894:	66 90                	xchg   %ax,%ax
  101896:	66 90                	xchg   %ax,%ax
  101898:	66 90                	xchg   %ax,%ax
  10189a:	66 90                	xchg   %ax,%ax
  10189c:	66 90                	xchg   %ax,%ax
  10189e:	66 90                	xchg   %ax,%ax
  1018a0:	66 90                	xchg   %ax,%ax
  1018a2:	66 90                	xchg   %ax,%ax
  1018a4:	66 90                	xchg   %ax,%ax
  1018a6:	66 90                	xchg   %ax,%ax
  1018a8:	66 90                	xchg   %ax,%ax
  1018aa:	66 90                	xchg   %ax,%ax
  1018ac:	66 90                	xchg   %ax,%ax
  1018ae:	66 90                	xchg   %ax,%ax
  1018b0:	66 90                	xchg   %ax,%ax
  1018b2:	66 90                	xchg   %ax,%ax
  1018b4:	66 90                	xchg   %ax,%ax
  1018b6:	66 90                	xchg   %ax,%ax
  1018b8:	66 90                	xchg   %ax,%ax
  1018ba:	66 90                	xchg   %ax,%ax
  1018bc:	66 90                	xchg   %ax,%ax
  1018be:	66 90                	xchg   %ax,%ax
  1018c0:	66 90                	xchg   %ax,%ax
  1018c2:	66 90                	xchg   %ax,%ax
  1018c4:	66 90                	xchg   %ax,%ax
  1018c6:	66 90                	xchg   %ax,%ax
  1018c8:	66 90                	xchg   %ax,%ax
  1018ca:	66 90                	xchg   %ax,%ax
  1018cc:	66 90                	xchg   %ax,%ax
  1018ce:	66 90                	xchg   %ax,%ax
  1018d0:	66 90                	xchg   %ax,%ax
  1018d2:	66 90                	xchg   %ax,%ax
  1018d4:	66 90                	xchg   %ax,%ax
  1018d6:	66 90                	xchg   %ax,%ax
  1018d8:	66 90                	xchg   %ax,%ax
  1018da:	66 90                	xchg   %ax,%ax
  1018dc:	66 90                	xchg   %ax,%ax
  1018de:	66 90                	xchg   %ax,%ax
  1018e0:	66 90                	xchg   %ax,%ax
  1018e2:	66 90                	xchg   %ax,%ax
  1018e4:	66 90                	xchg   %ax,%ax
  1018e6:	66 90                	xchg   %ax,%ax
  1018e8:	66 90                	xchg   %ax,%ax
  1018ea:	66 90                	xchg   %ax,%ax
  1018ec:	66 90                	xchg   %ax,%ax
  1018ee:	66 90                	xchg   %ax,%ax
  1018f0:	66 90                	xchg   %ax,%ax
  1018f2:	66 90                	xchg   %ax,%ax
  1018f4:	66 90                	xchg   %ax,%ax
  1018f6:	66 90                	xchg   %ax,%ax
  1018f8:	66 90                	xchg   %ax,%ax
  1018fa:	66 90                	xchg   %ax,%ax
  1018fc:	66 90                	xchg   %ax,%ax
  1018fe:	66 90                	xchg   %ax,%ax
  101900:	66 90                	xchg   %ax,%ax
  101902:	66 90                	xchg   %ax,%ax
  101904:	66 90                	xchg   %ax,%ax
  101906:	66 90                	xchg   %ax,%ax
  101908:	66 90                	xchg   %ax,%ax
  10190a:	66 90                	xchg   %ax,%ax
  10190c:	66 90                	xchg   %ax,%ax
  10190e:	66 90                	xchg   %ax,%ax
  101910:	66 90                	xchg   %ax,%ax
  101912:	66 90                	xchg   %ax,%ax
  101914:	66 90                	xchg   %ax,%ax
  101916:	66 90                	xchg   %ax,%ax
  101918:	66 90                	xchg   %ax,%ax
  10191a:	66 90                	xchg   %ax,%ax
  10191c:	66 90                	xchg   %ax,%ax
  10191e:	66 90                	xchg   %ax,%ax
  101920:	66 90                	xchg   %ax,%ax
  101922:	66 90                	xchg   %ax,%ax
  101924:	66 90                	xchg   %ax,%ax
  101926:	66 90                	xchg   %ax,%ax
  101928:	66 90                	xchg   %ax,%ax
  10192a:	66 90                	xchg   %ax,%ax
  10192c:	66 90                	xchg   %ax,%ax
  10192e:	66 90                	xchg   %ax,%ax
  101930:	66 90                	xchg   %ax,%ax
  101932:	66 90                	xchg   %ax,%ax
  101934:	66 90                	xchg   %ax,%ax
  101936:	66 90                	xchg   %ax,%ax
  101938:	66 90                	xchg   %ax,%ax
  10193a:	66 90                	xchg   %ax,%ax
  10193c:	66 90                	xchg   %ax,%ax
  10193e:	66 90                	xchg   %ax,%ax
  101940:	66 90                	xchg   %ax,%ax
  101942:	66 90                	xchg   %ax,%ax
  101944:	66 90                	xchg   %ax,%ax
  101946:	66 90                	xchg   %ax,%ax
  101948:	66 90                	xchg   %ax,%ax
  10194a:	66 90                	xchg   %ax,%ax
  10194c:	66 90                	xchg   %ax,%ax
  10194e:	66 90                	xchg   %ax,%ax
  101950:	66 90                	xchg   %ax,%ax
  101952:	66 90                	xchg   %ax,%ax
  101954:	66 90                	xchg   %ax,%ax
  101956:	66 90                	xchg   %ax,%ax
  101958:	66 90                	xchg   %ax,%ax
  10195a:	66 90                	xchg   %ax,%ax
  10195c:	66 90                	xchg   %ax,%ax
  10195e:	66 90                	xchg   %ax,%ax
  101960:	66 90                	xchg   %ax,%ax
  101962:	66 90                	xchg   %ax,%ax
  101964:	66 90                	xchg   %ax,%ax
  101966:	66 90                	xchg   %ax,%ax
  101968:	66 90                	xchg   %ax,%ax
  10196a:	66 90                	xchg   %ax,%ax
  10196c:	66 90                	xchg   %ax,%ax
  10196e:	66 90                	xchg   %ax,%ax
  101970:	66 90                	xchg   %ax,%ax
  101972:	66 90                	xchg   %ax,%ax
  101974:	66 90                	xchg   %ax,%ax
  101976:	66 90                	xchg   %ax,%ax
  101978:	66 90                	xchg   %ax,%ax
  10197a:	66 90                	xchg   %ax,%ax
  10197c:	66 90                	xchg   %ax,%ax
  10197e:	66 90                	xchg   %ax,%ax
  101980:	66 90                	xchg   %ax,%ax
  101982:	66 90                	xchg   %ax,%ax
  101984:	66 90                	xchg   %ax,%ax
  101986:	66 90                	xchg   %ax,%ax
  101988:	66 90                	xchg   %ax,%ax
  10198a:	66 90                	xchg   %ax,%ax
  10198c:	66 90                	xchg   %ax,%ax
  10198e:	66 90                	xchg   %ax,%ax
  101990:	66 90                	xchg   %ax,%ax
  101992:	66 90                	xchg   %ax,%ax
  101994:	66 90                	xchg   %ax,%ax
  101996:	66 90                	xchg   %ax,%ax
  101998:	66 90                	xchg   %ax,%ax
  10199a:	66 90                	xchg   %ax,%ax
  10199c:	66 90                	xchg   %ax,%ax
  10199e:	66 90                	xchg   %ax,%ax
  1019a0:	66 90                	xchg   %ax,%ax
  1019a2:	66 90                	xchg   %ax,%ax
  1019a4:	66 90                	xchg   %ax,%ax
  1019a6:	66 90                	xchg   %ax,%ax
  1019a8:	66 90                	xchg   %ax,%ax
  1019aa:	66 90                	xchg   %ax,%ax
  1019ac:	66 90                	xchg   %ax,%ax
  1019ae:	66 90                	xchg   %ax,%ax
  1019b0:	66 90                	xchg   %ax,%ax
  1019b2:	66 90                	xchg   %ax,%ax
  1019b4:	66 90                	xchg   %ax,%ax
  1019b6:	66 90                	xchg   %ax,%ax
  1019b8:	66 90                	xchg   %ax,%ax
  1019ba:	66 90                	xchg   %ax,%ax
  1019bc:	66 90                	xchg   %ax,%ax
  1019be:	66 90                	xchg   %ax,%ax
  1019c0:	66 90                	xchg   %ax,%ax
  1019c2:	66 90                	xchg   %ax,%ax
  1019c4:	66 90                	xchg   %ax,%ax
  1019c6:	66 90                	xchg   %ax,%ax
  1019c8:	66 90                	xchg   %ax,%ax
  1019ca:	66 90                	xchg   %ax,%ax
  1019cc:	66 90                	xchg   %ax,%ax
  1019ce:	66 90                	xchg   %ax,%ax
  1019d0:	66 90                	xchg   %ax,%ax
  1019d2:	66 90                	xchg   %ax,%ax
  1019d4:	66 90                	xchg   %ax,%ax
  1019d6:	66 90                	xchg   %ax,%ax
  1019d8:	66 90                	xchg   %ax,%ax
  1019da:	66 90                	xchg   %ax,%ax
  1019dc:	66 90                	xchg   %ax,%ax
  1019de:	66 90                	xchg   %ax,%ax
  1019e0:	66 90                	xchg   %ax,%ax
  1019e2:	66 90                	xchg   %ax,%ax
  1019e4:	66 90                	xchg   %ax,%ax
  1019e6:	66 90                	xchg   %ax,%ax
  1019e8:	66 90                	xchg   %ax,%ax
  1019ea:	66 90                	xchg   %ax,%ax
  1019ec:	66 90                	xchg   %ax,%ax
  1019ee:	66 90                	xchg   %ax,%ax
  1019f0:	66 90                	xchg   %ax,%ax
  1019f2:	66 90                	xchg   %ax,%ax
  1019f4:	66 90                	xchg   %ax,%ax
  1019f6:	66 90                	xchg   %ax,%ax
  1019f8:	66 90                	xchg   %ax,%ax
  1019fa:	66 90                	xchg   %ax,%ax
  1019fc:	66 90                	xchg   %ax,%ax
  1019fe:	66 90                	xchg   %ax,%ax
  101a00:	66 90                	xchg   %ax,%ax
  101a02:	66 90                	xchg   %ax,%ax
  101a04:	66 90                	xchg   %ax,%ax
  101a06:	66 90                	xchg   %ax,%ax
  101a08:	66 90                	xchg   %ax,%ax
  101a0a:	66 90                	xchg   %ax,%ax
  101a0c:	66 90                	xchg   %ax,%ax
  101a0e:	66 90                	xchg   %ax,%ax
  101a10:	66 90                	xchg   %ax,%ax
  101a12:	66 90                	xchg   %ax,%ax
  101a14:	66 90                	xchg   %ax,%ax
  101a16:	66 90                	xchg   %ax,%ax
  101a18:	66 90                	xchg   %ax,%ax
  101a1a:	66 90                	xchg   %ax,%ax
  101a1c:	66 90                	xchg   %ax,%ax
  101a1e:	66 90                	xchg   %ax,%ax
  101a20:	66 90                	xchg   %ax,%ax
  101a22:	66 90                	xchg   %ax,%ax
  101a24:	66 90                	xchg   %ax,%ax
  101a26:	66 90                	xchg   %ax,%ax
  101a28:	66 90                	xchg   %ax,%ax
  101a2a:	66 90                	xchg   %ax,%ax
  101a2c:	66 90                	xchg   %ax,%ax
  101a2e:	66 90                	xchg   %ax,%ax
  101a30:	66 90                	xchg   %ax,%ax
  101a32:	66 90                	xchg   %ax,%ax
  101a34:	66 90                	xchg   %ax,%ax
  101a36:	66 90                	xchg   %ax,%ax
  101a38:	66 90                	xchg   %ax,%ax
  101a3a:	66 90                	xchg   %ax,%ax
  101a3c:	66 90                	xchg   %ax,%ax
  101a3e:	66 90                	xchg   %ax,%ax
  101a40:	66 90                	xchg   %ax,%ax
  101a42:	66 90                	xchg   %ax,%ax
  101a44:	66 90                	xchg   %ax,%ax
  101a46:	66 90                	xchg   %ax,%ax
  101a48:	66 90                	xchg   %ax,%ax
  101a4a:	66 90                	xchg   %ax,%ax
  101a4c:	66 90                	xchg   %ax,%ax
  101a4e:	66 90                	xchg   %ax,%ax
  101a50:	66 90                	xchg   %ax,%ax
  101a52:	66 90                	xchg   %ax,%ax
  101a54:	66 90                	xchg   %ax,%ax
  101a56:	66 90                	xchg   %ax,%ax
  101a58:	66 90                	xchg   %ax,%ax
  101a5a:	66 90                	xchg   %ax,%ax
  101a5c:	66 90                	xchg   %ax,%ax
  101a5e:	66 90                	xchg   %ax,%ax
  101a60:	66 90                	xchg   %ax,%ax
  101a62:	66 90                	xchg   %ax,%ax
  101a64:	66 90                	xchg   %ax,%ax
  101a66:	66 90                	xchg   %ax,%ax
  101a68:	66 90                	xchg   %ax,%ax
  101a6a:	66 90                	xchg   %ax,%ax
  101a6c:	66 90                	xchg   %ax,%ax
  101a6e:	66 90                	xchg   %ax,%ax
  101a70:	66 90                	xchg   %ax,%ax
  101a72:	66 90                	xchg   %ax,%ax
  101a74:	66 90                	xchg   %ax,%ax
  101a76:	66 90                	xchg   %ax,%ax
  101a78:	66 90                	xchg   %ax,%ax
  101a7a:	66 90                	xchg   %ax,%ax
  101a7c:	66 90                	xchg   %ax,%ax
  101a7e:	66 90                	xchg   %ax,%ax
  101a80:	66 90                	xchg   %ax,%ax
  101a82:	66 90                	xchg   %ax,%ax
  101a84:	66 90                	xchg   %ax,%ax
  101a86:	66 90                	xchg   %ax,%ax
  101a88:	66 90                	xchg   %ax,%ax
  101a8a:	66 90                	xchg   %ax,%ax
  101a8c:	66 90                	xchg   %ax,%ax
  101a8e:	66 90                	xchg   %ax,%ax
  101a90:	66 90                	xchg   %ax,%ax
  101a92:	66 90                	xchg   %ax,%ax
  101a94:	66 90                	xchg   %ax,%ax
  101a96:	66 90                	xchg   %ax,%ax
  101a98:	66 90                	xchg   %ax,%ax
  101a9a:	66 90                	xchg   %ax,%ax
  101a9c:	66 90                	xchg   %ax,%ax
  101a9e:	66 90                	xchg   %ax,%ax
  101aa0:	66 90                	xchg   %ax,%ax
  101aa2:	66 90                	xchg   %ax,%ax
  101aa4:	66 90                	xchg   %ax,%ax
  101aa6:	66 90                	xchg   %ax,%ax
  101aa8:	66 90                	xchg   %ax,%ax
  101aaa:	66 90                	xchg   %ax,%ax
  101aac:	66 90                	xchg   %ax,%ax
  101aae:	66 90                	xchg   %ax,%ax
  101ab0:	66 90                	xchg   %ax,%ax
  101ab2:	66 90                	xchg   %ax,%ax
  101ab4:	66 90                	xchg   %ax,%ax
  101ab6:	66 90                	xchg   %ax,%ax
  101ab8:	66 90                	xchg   %ax,%ax
  101aba:	66 90                	xchg   %ax,%ax
  101abc:	66 90                	xchg   %ax,%ax
  101abe:	66 90                	xchg   %ax,%ax
  101ac0:	66 90                	xchg   %ax,%ax
  101ac2:	66 90                	xchg   %ax,%ax
  101ac4:	66 90                	xchg   %ax,%ax
  101ac6:	66 90                	xchg   %ax,%ax
  101ac8:	66 90                	xchg   %ax,%ax
  101aca:	66 90                	xchg   %ax,%ax
  101acc:	66 90                	xchg   %ax,%ax
  101ace:	66 90                	xchg   %ax,%ax
  101ad0:	66 90                	xchg   %ax,%ax
  101ad2:	66 90                	xchg   %ax,%ax
  101ad4:	66 90                	xchg   %ax,%ax
  101ad6:	66 90                	xchg   %ax,%ax
  101ad8:	66 90                	xchg   %ax,%ax
  101ada:	66 90                	xchg   %ax,%ax
  101adc:	66 90                	xchg   %ax,%ax
  101ade:	66 90                	xchg   %ax,%ax
  101ae0:	66 90                	xchg   %ax,%ax
  101ae2:	66 90                	xchg   %ax,%ax
  101ae4:	66 90                	xchg   %ax,%ax
  101ae6:	66 90                	xchg   %ax,%ax
  101ae8:	66 90                	xchg   %ax,%ax
  101aea:	66 90                	xchg   %ax,%ax
  101aec:	66 90                	xchg   %ax,%ax
  101aee:	66 90                	xchg   %ax,%ax
  101af0:	66 90                	xchg   %ax,%ax
  101af2:	66 90                	xchg   %ax,%ax
  101af4:	66 90                	xchg   %ax,%ax
  101af6:	66 90                	xchg   %ax,%ax
  101af8:	66 90                	xchg   %ax,%ax
  101afa:	66 90                	xchg   %ax,%ax
  101afc:	66 90                	xchg   %ax,%ax
  101afe:	66 90                	xchg   %ax,%ax
  101b00:	66 90                	xchg   %ax,%ax
  101b02:	66 90                	xchg   %ax,%ax
  101b04:	66 90                	xchg   %ax,%ax
  101b06:	66 90                	xchg   %ax,%ax
  101b08:	66 90                	xchg   %ax,%ax
  101b0a:	66 90                	xchg   %ax,%ax
  101b0c:	66 90                	xchg   %ax,%ax
  101b0e:	66 90                	xchg   %ax,%ax
  101b10:	66 90                	xchg   %ax,%ax
  101b12:	66 90                	xchg   %ax,%ax
  101b14:	66 90                	xchg   %ax,%ax
  101b16:	66 90                	xchg   %ax,%ax
  101b18:	66 90                	xchg   %ax,%ax
  101b1a:	66 90                	xchg   %ax,%ax
  101b1c:	66 90                	xchg   %ax,%ax
  101b1e:	66 90                	xchg   %ax,%ax
  101b20:	66 90                	xchg   %ax,%ax
  101b22:	66 90                	xchg   %ax,%ax
  101b24:	66 90                	xchg   %ax,%ax
  101b26:	66 90                	xchg   %ax,%ax
  101b28:	66 90                	xchg   %ax,%ax
  101b2a:	66 90                	xchg   %ax,%ax
  101b2c:	66 90                	xchg   %ax,%ax
  101b2e:	66 90                	xchg   %ax,%ax
  101b30:	66 90                	xchg   %ax,%ax
  101b32:	66 90                	xchg   %ax,%ax
  101b34:	66 90                	xchg   %ax,%ax
  101b36:	66 90                	xchg   %ax,%ax
  101b38:	66 90                	xchg   %ax,%ax
  101b3a:	66 90                	xchg   %ax,%ax
  101b3c:	66 90                	xchg   %ax,%ax
  101b3e:	66 90                	xchg   %ax,%ax
  101b40:	66 90                	xchg   %ax,%ax
  101b42:	66 90                	xchg   %ax,%ax
  101b44:	66 90                	xchg   %ax,%ax
  101b46:	66 90                	xchg   %ax,%ax
  101b48:	66 90                	xchg   %ax,%ax
  101b4a:	66 90                	xchg   %ax,%ax
  101b4c:	66 90                	xchg   %ax,%ax
  101b4e:	66 90                	xchg   %ax,%ax
  101b50:	66 90                	xchg   %ax,%ax
  101b52:	66 90                	xchg   %ax,%ax
  101b54:	66 90                	xchg   %ax,%ax
  101b56:	66 90                	xchg   %ax,%ax
  101b58:	66 90                	xchg   %ax,%ax
  101b5a:	66 90                	xchg   %ax,%ax
  101b5c:	66 90                	xchg   %ax,%ax
  101b5e:	66 90                	xchg   %ax,%ax
  101b60:	66 90                	xchg   %ax,%ax
  101b62:	66 90                	xchg   %ax,%ax
  101b64:	66 90                	xchg   %ax,%ax
  101b66:	66 90                	xchg   %ax,%ax
  101b68:	66 90                	xchg   %ax,%ax
  101b6a:	66 90                	xchg   %ax,%ax
  101b6c:	66 90                	xchg   %ax,%ax
  101b6e:	66 90                	xchg   %ax,%ax
  101b70:	66 90                	xchg   %ax,%ax
  101b72:	66 90                	xchg   %ax,%ax
  101b74:	66 90                	xchg   %ax,%ax
  101b76:	66 90                	xchg   %ax,%ax
  101b78:	66 90                	xchg   %ax,%ax
  101b7a:	66 90                	xchg   %ax,%ax
  101b7c:	66 90                	xchg   %ax,%ax
  101b7e:	66 90                	xchg   %ax,%ax
  101b80:	66 90                	xchg   %ax,%ax
  101b82:	66 90                	xchg   %ax,%ax
  101b84:	66 90                	xchg   %ax,%ax
  101b86:	66 90                	xchg   %ax,%ax
  101b88:	66 90                	xchg   %ax,%ax
  101b8a:	66 90                	xchg   %ax,%ax
  101b8c:	66 90                	xchg   %ax,%ax
  101b8e:	66 90                	xchg   %ax,%ax
  101b90:	66 90                	xchg   %ax,%ax
  101b92:	66 90                	xchg   %ax,%ax
  101b94:	66 90                	xchg   %ax,%ax
  101b96:	66 90                	xchg   %ax,%ax
  101b98:	66 90                	xchg   %ax,%ax
  101b9a:	66 90                	xchg   %ax,%ax
  101b9c:	66 90                	xchg   %ax,%ax
  101b9e:	66 90                	xchg   %ax,%ax
  101ba0:	66 90                	xchg   %ax,%ax
  101ba2:	66 90                	xchg   %ax,%ax
  101ba4:	66 90                	xchg   %ax,%ax
  101ba6:	66 90                	xchg   %ax,%ax
  101ba8:	66 90                	xchg   %ax,%ax
  101baa:	66 90                	xchg   %ax,%ax
  101bac:	66 90                	xchg   %ax,%ax
  101bae:	66 90                	xchg   %ax,%ax
  101bb0:	66 90                	xchg   %ax,%ax
  101bb2:	66 90                	xchg   %ax,%ax
  101bb4:	66 90                	xchg   %ax,%ax
  101bb6:	66 90                	xchg   %ax,%ax
  101bb8:	66 90                	xchg   %ax,%ax
  101bba:	66 90                	xchg   %ax,%ax
  101bbc:	66 90                	xchg   %ax,%ax
  101bbe:	66 90                	xchg   %ax,%ax
  101bc0:	66 90                	xchg   %ax,%ax
  101bc2:	66 90                	xchg   %ax,%ax
  101bc4:	66 90                	xchg   %ax,%ax
  101bc6:	66 90                	xchg   %ax,%ax
  101bc8:	66 90                	xchg   %ax,%ax
  101bca:	66 90                	xchg   %ax,%ax
  101bcc:	66 90                	xchg   %ax,%ax
  101bce:	66 90                	xchg   %ax,%ax
  101bd0:	66 90                	xchg   %ax,%ax
  101bd2:	66 90                	xchg   %ax,%ax
  101bd4:	66 90                	xchg   %ax,%ax
  101bd6:	66 90                	xchg   %ax,%ax
  101bd8:	66 90                	xchg   %ax,%ax
  101bda:	66 90                	xchg   %ax,%ax
  101bdc:	66 90                	xchg   %ax,%ax
  101bde:	66 90                	xchg   %ax,%ax
  101be0:	66 90                	xchg   %ax,%ax
  101be2:	66 90                	xchg   %ax,%ax
  101be4:	66 90                	xchg   %ax,%ax
  101be6:	66 90                	xchg   %ax,%ax
  101be8:	66 90                	xchg   %ax,%ax
  101bea:	66 90                	xchg   %ax,%ax
  101bec:	66 90                	xchg   %ax,%ax
  101bee:	66 90                	xchg   %ax,%ax
  101bf0:	66 90                	xchg   %ax,%ax
  101bf2:	66 90                	xchg   %ax,%ax
  101bf4:	66 90                	xchg   %ax,%ax
  101bf6:	66 90                	xchg   %ax,%ax
  101bf8:	66 90                	xchg   %ax,%ax
  101bfa:	66 90                	xchg   %ax,%ax
  101bfc:	66 90                	xchg   %ax,%ax
  101bfe:	66 90                	xchg   %ax,%ax
  101c00:	66 90                	xchg   %ax,%ax
  101c02:	66 90                	xchg   %ax,%ax
  101c04:	66 90                	xchg   %ax,%ax
  101c06:	66 90                	xchg   %ax,%ax
  101c08:	66 90                	xchg   %ax,%ax
  101c0a:	66 90                	xchg   %ax,%ax
  101c0c:	66 90                	xchg   %ax,%ax
  101c0e:	66 90                	xchg   %ax,%ax
  101c10:	66 90                	xchg   %ax,%ax
  101c12:	66 90                	xchg   %ax,%ax
  101c14:	66 90                	xchg   %ax,%ax
  101c16:	66 90                	xchg   %ax,%ax
  101c18:	66 90                	xchg   %ax,%ax
  101c1a:	66 90                	xchg   %ax,%ax
  101c1c:	66 90                	xchg   %ax,%ax
  101c1e:	66 90                	xchg   %ax,%ax
  101c20:	66 90                	xchg   %ax,%ax
  101c22:	66 90                	xchg   %ax,%ax
  101c24:	66 90                	xchg   %ax,%ax
  101c26:	66 90                	xchg   %ax,%ax
  101c28:	66 90                	xchg   %ax,%ax
  101c2a:	66 90                	xchg   %ax,%ax
  101c2c:	66 90                	xchg   %ax,%ax
  101c2e:	66 90                	xchg   %ax,%ax
  101c30:	66 90                	xchg   %ax,%ax
  101c32:	66 90                	xchg   %ax,%ax
  101c34:	66 90                	xchg   %ax,%ax
  101c36:	66 90                	xchg   %ax,%ax
  101c38:	66 90                	xchg   %ax,%ax
  101c3a:	66 90                	xchg   %ax,%ax
  101c3c:	66 90                	xchg   %ax,%ax
  101c3e:	66 90                	xchg   %ax,%ax
  101c40:	66 90                	xchg   %ax,%ax
  101c42:	66 90                	xchg   %ax,%ax
  101c44:	66 90                	xchg   %ax,%ax
  101c46:	66 90                	xchg   %ax,%ax
  101c48:	66 90                	xchg   %ax,%ax
  101c4a:	66 90                	xchg   %ax,%ax
  101c4c:	66 90                	xchg   %ax,%ax
  101c4e:	66 90                	xchg   %ax,%ax
  101c50:	66 90                	xchg   %ax,%ax
  101c52:	66 90                	xchg   %ax,%ax
  101c54:	66 90                	xchg   %ax,%ax
  101c56:	66 90                	xchg   %ax,%ax
  101c58:	66 90                	xchg   %ax,%ax
  101c5a:	66 90                	xchg   %ax,%ax
  101c5c:	66 90                	xchg   %ax,%ax
  101c5e:	66 90                	xchg   %ax,%ax
  101c60:	66 90                	xchg   %ax,%ax
  101c62:	66 90                	xchg   %ax,%ax
  101c64:	66 90                	xchg   %ax,%ax
  101c66:	66 90                	xchg   %ax,%ax
  101c68:	66 90                	xchg   %ax,%ax
  101c6a:	66 90                	xchg   %ax,%ax
  101c6c:	66 90                	xchg   %ax,%ax
  101c6e:	66 90                	xchg   %ax,%ax
  101c70:	66 90                	xchg   %ax,%ax
  101c72:	66 90                	xchg   %ax,%ax
  101c74:	66 90                	xchg   %ax,%ax
  101c76:	66 90                	xchg   %ax,%ax
  101c78:	66 90                	xchg   %ax,%ax
  101c7a:	66 90                	xchg   %ax,%ax
  101c7c:	66 90                	xchg   %ax,%ax
  101c7e:	66 90                	xchg   %ax,%ax
  101c80:	66 90                	xchg   %ax,%ax
  101c82:	66 90                	xchg   %ax,%ax
  101c84:	66 90                	xchg   %ax,%ax
  101c86:	66 90                	xchg   %ax,%ax
  101c88:	66 90                	xchg   %ax,%ax
  101c8a:	66 90                	xchg   %ax,%ax
  101c8c:	66 90                	xchg   %ax,%ax
  101c8e:	66 90                	xchg   %ax,%ax
  101c90:	66 90                	xchg   %ax,%ax
  101c92:	66 90                	xchg   %ax,%ax
  101c94:	66 90                	xchg   %ax,%ax
  101c96:	66 90                	xchg   %ax,%ax
  101c98:	66 90                	xchg   %ax,%ax
  101c9a:	66 90                	xchg   %ax,%ax
  101c9c:	66 90                	xchg   %ax,%ax
  101c9e:	66 90                	xchg   %ax,%ax
  101ca0:	66 90                	xchg   %ax,%ax
  101ca2:	66 90                	xchg   %ax,%ax
  101ca4:	66 90                	xchg   %ax,%ax
  101ca6:	66 90                	xchg   %ax,%ax
  101ca8:	66 90                	xchg   %ax,%ax
  101caa:	66 90                	xchg   %ax,%ax
  101cac:	66 90                	xchg   %ax,%ax
  101cae:	66 90                	xchg   %ax,%ax
  101cb0:	66 90                	xchg   %ax,%ax
  101cb2:	66 90                	xchg   %ax,%ax
  101cb4:	66 90                	xchg   %ax,%ax
  101cb6:	66 90                	xchg   %ax,%ax
  101cb8:	66 90                	xchg   %ax,%ax
  101cba:	66 90                	xchg   %ax,%ax
  101cbc:	66 90                	xchg   %ax,%ax
  101cbe:	66 90                	xchg   %ax,%ax
  101cc0:	66 90                	xchg   %ax,%ax
  101cc2:	66 90                	xchg   %ax,%ax
  101cc4:	66 90                	xchg   %ax,%ax
  101cc6:	66 90                	xchg   %ax,%ax
  101cc8:	66 90                	xchg   %ax,%ax
  101cca:	66 90                	xchg   %ax,%ax
  101ccc:	66 90                	xchg   %ax,%ax
  101cce:	66 90                	xchg   %ax,%ax
  101cd0:	66 90                	xchg   %ax,%ax
  101cd2:	66 90                	xchg   %ax,%ax
  101cd4:	66 90                	xchg   %ax,%ax
  101cd6:	66 90                	xchg   %ax,%ax
  101cd8:	66 90                	xchg   %ax,%ax
  101cda:	66 90                	xchg   %ax,%ax
  101cdc:	66 90                	xchg   %ax,%ax
  101cde:	66 90                	xchg   %ax,%ax
  101ce0:	66 90                	xchg   %ax,%ax
  101ce2:	66 90                	xchg   %ax,%ax
  101ce4:	66 90                	xchg   %ax,%ax
  101ce6:	66 90                	xchg   %ax,%ax
  101ce8:	66 90                	xchg   %ax,%ax
  101cea:	66 90                	xchg   %ax,%ax
  101cec:	66 90                	xchg   %ax,%ax
  101cee:	66 90                	xchg   %ax,%ax
  101cf0:	66 90                	xchg   %ax,%ax
  101cf2:	66 90                	xchg   %ax,%ax
  101cf4:	66 90                	xchg   %ax,%ax
  101cf6:	66 90                	xchg   %ax,%ax
  101cf8:	66 90                	xchg   %ax,%ax
  101cfa:	66 90                	xchg   %ax,%ax
  101cfc:	66 90                	xchg   %ax,%ax
  101cfe:	66 90                	xchg   %ax,%ax
  101d00:	66 90                	xchg   %ax,%ax
  101d02:	66 90                	xchg   %ax,%ax
  101d04:	66 90                	xchg   %ax,%ax
  101d06:	66 90                	xchg   %ax,%ax
  101d08:	66 90                	xchg   %ax,%ax
  101d0a:	66 90                	xchg   %ax,%ax
  101d0c:	66 90                	xchg   %ax,%ax
  101d0e:	66 90                	xchg   %ax,%ax
  101d10:	66 90                	xchg   %ax,%ax
  101d12:	66 90                	xchg   %ax,%ax
  101d14:	66 90                	xchg   %ax,%ax
  101d16:	66 90                	xchg   %ax,%ax
  101d18:	66 90                	xchg   %ax,%ax
  101d1a:	66 90                	xchg   %ax,%ax
  101d1c:	66 90                	xchg   %ax,%ax
  101d1e:	66 90                	xchg   %ax,%ax
  101d20:	66 90                	xchg   %ax,%ax
  101d22:	66 90                	xchg   %ax,%ax
  101d24:	66 90                	xchg   %ax,%ax
  101d26:	66 90                	xchg   %ax,%ax
  101d28:	66 90                	xchg   %ax,%ax
  101d2a:	66 90                	xchg   %ax,%ax
  101d2c:	66 90                	xchg   %ax,%ax
  101d2e:	66 90                	xchg   %ax,%ax
  101d30:	66 90                	xchg   %ax,%ax
  101d32:	66 90                	xchg   %ax,%ax
  101d34:	66 90                	xchg   %ax,%ax
  101d36:	66 90                	xchg   %ax,%ax
  101d38:	66 90                	xchg   %ax,%ax
  101d3a:	66 90                	xchg   %ax,%ax
  101d3c:	66 90                	xchg   %ax,%ax
  101d3e:	66 90                	xchg   %ax,%ax
  101d40:	66 90                	xchg   %ax,%ax
  101d42:	66 90                	xchg   %ax,%ax
  101d44:	66 90                	xchg   %ax,%ax
  101d46:	66 90                	xchg   %ax,%ax
  101d48:	66 90                	xchg   %ax,%ax
  101d4a:	66 90                	xchg   %ax,%ax
  101d4c:	66 90                	xchg   %ax,%ax
  101d4e:	66 90                	xchg   %ax,%ax
  101d50:	66 90                	xchg   %ax,%ax
  101d52:	66 90                	xchg   %ax,%ax
  101d54:	66 90                	xchg   %ax,%ax
  101d56:	66 90                	xchg   %ax,%ax
  101d58:	66 90                	xchg   %ax,%ax
  101d5a:	66 90                	xchg   %ax,%ax
  101d5c:	66 90                	xchg   %ax,%ax
  101d5e:	66 90                	xchg   %ax,%ax
  101d60:	66 90                	xchg   %ax,%ax
  101d62:	66 90                	xchg   %ax,%ax
  101d64:	66 90                	xchg   %ax,%ax
  101d66:	66 90                	xchg   %ax,%ax
  101d68:	66 90                	xchg   %ax,%ax
  101d6a:	66 90                	xchg   %ax,%ax
  101d6c:	66 90                	xchg   %ax,%ax
  101d6e:	66 90                	xchg   %ax,%ax
  101d70:	66 90                	xchg   %ax,%ax
  101d72:	66 90                	xchg   %ax,%ax
  101d74:	66 90                	xchg   %ax,%ax
  101d76:	66 90                	xchg   %ax,%ax
  101d78:	66 90                	xchg   %ax,%ax
  101d7a:	66 90                	xchg   %ax,%ax
  101d7c:	66 90                	xchg   %ax,%ax
  101d7e:	66 90                	xchg   %ax,%ax
  101d80:	66 90                	xchg   %ax,%ax
  101d82:	66 90                	xchg   %ax,%ax
  101d84:	66 90                	xchg   %ax,%ax
  101d86:	66 90                	xchg   %ax,%ax
  101d88:	66 90                	xchg   %ax,%ax
  101d8a:	66 90                	xchg   %ax,%ax
  101d8c:	66 90                	xchg   %ax,%ax
  101d8e:	66 90                	xchg   %ax,%ax
  101d90:	66 90                	xchg   %ax,%ax
  101d92:	66 90                	xchg   %ax,%ax
  101d94:	66 90                	xchg   %ax,%ax
  101d96:	66 90                	xchg   %ax,%ax
  101d98:	66 90                	xchg   %ax,%ax
  101d9a:	66 90                	xchg   %ax,%ax
  101d9c:	66 90                	xchg   %ax,%ax
  101d9e:	66 90                	xchg   %ax,%ax
  101da0:	66 90                	xchg   %ax,%ax
  101da2:	66 90                	xchg   %ax,%ax
  101da4:	66 90                	xchg   %ax,%ax
  101da6:	66 90                	xchg   %ax,%ax
  101da8:	66 90                	xchg   %ax,%ax
  101daa:	66 90                	xchg   %ax,%ax
  101dac:	66 90                	xchg   %ax,%ax
  101dae:	66 90                	xchg   %ax,%ax
  101db0:	66 90                	xchg   %ax,%ax
  101db2:	66 90                	xchg   %ax,%ax
  101db4:	66 90                	xchg   %ax,%ax
  101db6:	66 90                	xchg   %ax,%ax
  101db8:	66 90                	xchg   %ax,%ax
  101dba:	66 90                	xchg   %ax,%ax
  101dbc:	66 90                	xchg   %ax,%ax
  101dbe:	66 90                	xchg   %ax,%ax
  101dc0:	66 90                	xchg   %ax,%ax
  101dc2:	66 90                	xchg   %ax,%ax
  101dc4:	66 90                	xchg   %ax,%ax
  101dc6:	66 90                	xchg   %ax,%ax
  101dc8:	66 90                	xchg   %ax,%ax
  101dca:	66 90                	xchg   %ax,%ax
  101dcc:	66 90                	xchg   %ax,%ax
  101dce:	66 90                	xchg   %ax,%ax
  101dd0:	66 90                	xchg   %ax,%ax
  101dd2:	66 90                	xchg   %ax,%ax
  101dd4:	66 90                	xchg   %ax,%ax
  101dd6:	66 90                	xchg   %ax,%ax
  101dd8:	66 90                	xchg   %ax,%ax
  101dda:	66 90                	xchg   %ax,%ax
  101ddc:	66 90                	xchg   %ax,%ax
  101dde:	66 90                	xchg   %ax,%ax
  101de0:	66 90                	xchg   %ax,%ax
  101de2:	66 90                	xchg   %ax,%ax
  101de4:	66 90                	xchg   %ax,%ax
  101de6:	66 90                	xchg   %ax,%ax
  101de8:	66 90                	xchg   %ax,%ax
  101dea:	66 90                	xchg   %ax,%ax
  101dec:	66 90                	xchg   %ax,%ax
  101dee:	66 90                	xchg   %ax,%ax
  101df0:	66 90                	xchg   %ax,%ax
  101df2:	66 90                	xchg   %ax,%ax
  101df4:	66 90                	xchg   %ax,%ax
  101df6:	66 90                	xchg   %ax,%ax
  101df8:	66 90                	xchg   %ax,%ax
  101dfa:	66 90                	xchg   %ax,%ax
  101dfc:	66 90                	xchg   %ax,%ax
  101dfe:	66 90                	xchg   %ax,%ax
  101e00:	66 90                	xchg   %ax,%ax
  101e02:	66 90                	xchg   %ax,%ax
  101e04:	66 90                	xchg   %ax,%ax
  101e06:	66 90                	xchg   %ax,%ax
  101e08:	66 90                	xchg   %ax,%ax
  101e0a:	66 90                	xchg   %ax,%ax
  101e0c:	66 90                	xchg   %ax,%ax
  101e0e:	66 90                	xchg   %ax,%ax
  101e10:	66 90                	xchg   %ax,%ax
  101e12:	66 90                	xchg   %ax,%ax
  101e14:	66 90                	xchg   %ax,%ax
  101e16:	66 90                	xchg   %ax,%ax
  101e18:	66 90                	xchg   %ax,%ax
  101e1a:	66 90                	xchg   %ax,%ax
  101e1c:	66 90                	xchg   %ax,%ax
  101e1e:	66 90                	xchg   %ax,%ax
  101e20:	66 90                	xchg   %ax,%ax
  101e22:	66 90                	xchg   %ax,%ax
  101e24:	66 90                	xchg   %ax,%ax
  101e26:	66 90                	xchg   %ax,%ax
  101e28:	66 90                	xchg   %ax,%ax
  101e2a:	66 90                	xchg   %ax,%ax
  101e2c:	66 90                	xchg   %ax,%ax
  101e2e:	66 90                	xchg   %ax,%ax
  101e30:	66 90                	xchg   %ax,%ax
  101e32:	66 90                	xchg   %ax,%ax
  101e34:	66 90                	xchg   %ax,%ax
  101e36:	66 90                	xchg   %ax,%ax
  101e38:	66 90                	xchg   %ax,%ax
  101e3a:	66 90                	xchg   %ax,%ax
  101e3c:	66 90                	xchg   %ax,%ax
  101e3e:	66 90                	xchg   %ax,%ax
  101e40:	66 90                	xchg   %ax,%ax
  101e42:	66 90                	xchg   %ax,%ax
  101e44:	66 90                	xchg   %ax,%ax
  101e46:	66 90                	xchg   %ax,%ax
  101e48:	66 90                	xchg   %ax,%ax
  101e4a:	66 90                	xchg   %ax,%ax
  101e4c:	66 90                	xchg   %ax,%ax
  101e4e:	66 90                	xchg   %ax,%ax
  101e50:	66 90                	xchg   %ax,%ax
  101e52:	66 90                	xchg   %ax,%ax
  101e54:	66 90                	xchg   %ax,%ax
  101e56:	66 90                	xchg   %ax,%ax
  101e58:	66 90                	xchg   %ax,%ax
  101e5a:	66 90                	xchg   %ax,%ax
  101e5c:	66 90                	xchg   %ax,%ax
  101e5e:	66 90                	xchg   %ax,%ax
  101e60:	66 90                	xchg   %ax,%ax
  101e62:	66 90                	xchg   %ax,%ax
  101e64:	66 90                	xchg   %ax,%ax
  101e66:	66 90                	xchg   %ax,%ax
  101e68:	66 90                	xchg   %ax,%ax
  101e6a:	66 90                	xchg   %ax,%ax
  101e6c:	66 90                	xchg   %ax,%ax
  101e6e:	66 90                	xchg   %ax,%ax
  101e70:	66 90                	xchg   %ax,%ax
  101e72:	66 90                	xchg   %ax,%ax
  101e74:	66 90                	xchg   %ax,%ax
  101e76:	66 90                	xchg   %ax,%ax
  101e78:	66 90                	xchg   %ax,%ax
  101e7a:	66 90                	xchg   %ax,%ax
  101e7c:	66 90                	xchg   %ax,%ax
  101e7e:	66 90                	xchg   %ax,%ax
  101e80:	66 90                	xchg   %ax,%ax
  101e82:	66 90                	xchg   %ax,%ax
  101e84:	66 90                	xchg   %ax,%ax
  101e86:	66 90                	xchg   %ax,%ax
  101e88:	66 90                	xchg   %ax,%ax
  101e8a:	66 90                	xchg   %ax,%ax
  101e8c:	66 90                	xchg   %ax,%ax
  101e8e:	66 90                	xchg   %ax,%ax
  101e90:	66 90                	xchg   %ax,%ax
  101e92:	66 90                	xchg   %ax,%ax
  101e94:	66 90                	xchg   %ax,%ax
  101e96:	66 90                	xchg   %ax,%ax
  101e98:	66 90                	xchg   %ax,%ax
  101e9a:	66 90                	xchg   %ax,%ax
  101e9c:	66 90                	xchg   %ax,%ax
  101e9e:	66 90                	xchg   %ax,%ax
  101ea0:	66 90                	xchg   %ax,%ax
  101ea2:	66 90                	xchg   %ax,%ax
  101ea4:	66 90                	xchg   %ax,%ax
  101ea6:	66 90                	xchg   %ax,%ax
  101ea8:	66 90                	xchg   %ax,%ax
  101eaa:	66 90                	xchg   %ax,%ax
  101eac:	66 90                	xchg   %ax,%ax
  101eae:	66 90                	xchg   %ax,%ax
  101eb0:	66 90                	xchg   %ax,%ax
  101eb2:	66 90                	xchg   %ax,%ax
  101eb4:	66 90                	xchg   %ax,%ax
  101eb6:	66 90                	xchg   %ax,%ax
  101eb8:	66 90                	xchg   %ax,%ax
  101eba:	66 90                	xchg   %ax,%ax
  101ebc:	66 90                	xchg   %ax,%ax
  101ebe:	66 90                	xchg   %ax,%ax
  101ec0:	66 90                	xchg   %ax,%ax
  101ec2:	66 90                	xchg   %ax,%ax
  101ec4:	66 90                	xchg   %ax,%ax
  101ec6:	66 90                	xchg   %ax,%ax
  101ec8:	66 90                	xchg   %ax,%ax
  101eca:	66 90                	xchg   %ax,%ax
  101ecc:	66 90                	xchg   %ax,%ax
  101ece:	66 90                	xchg   %ax,%ax
  101ed0:	66 90                	xchg   %ax,%ax
  101ed2:	66 90                	xchg   %ax,%ax
  101ed4:	66 90                	xchg   %ax,%ax
  101ed6:	66 90                	xchg   %ax,%ax
  101ed8:	66 90                	xchg   %ax,%ax
  101eda:	66 90                	xchg   %ax,%ax
  101edc:	66 90                	xchg   %ax,%ax
  101ede:	66 90                	xchg   %ax,%ax
  101ee0:	66 90                	xchg   %ax,%ax
  101ee2:	66 90                	xchg   %ax,%ax
  101ee4:	66 90                	xchg   %ax,%ax
  101ee6:	66 90                	xchg   %ax,%ax
  101ee8:	66 90                	xchg   %ax,%ax
  101eea:	66 90                	xchg   %ax,%ax
  101eec:	66 90                	xchg   %ax,%ax
  101eee:	66 90                	xchg   %ax,%ax
  101ef0:	66 90                	xchg   %ax,%ax
  101ef2:	66 90                	xchg   %ax,%ax
  101ef4:	66 90                	xchg   %ax,%ax
  101ef6:	66 90                	xchg   %ax,%ax
  101ef8:	66 90                	xchg   %ax,%ax
  101efa:	66 90                	xchg   %ax,%ax
  101efc:	66 90                	xchg   %ax,%ax
  101efe:	66 90                	xchg   %ax,%ax
  101f00:	66 90                	xchg   %ax,%ax
  101f02:	66 90                	xchg   %ax,%ax
  101f04:	66 90                	xchg   %ax,%ax
  101f06:	66 90                	xchg   %ax,%ax
  101f08:	66 90                	xchg   %ax,%ax
  101f0a:	66 90                	xchg   %ax,%ax
  101f0c:	66 90                	xchg   %ax,%ax
  101f0e:	66 90                	xchg   %ax,%ax
  101f10:	66 90                	xchg   %ax,%ax
  101f12:	66 90                	xchg   %ax,%ax
  101f14:	66 90                	xchg   %ax,%ax
  101f16:	66 90                	xchg   %ax,%ax
  101f18:	66 90                	xchg   %ax,%ax
  101f1a:	66 90                	xchg   %ax,%ax
  101f1c:	66 90                	xchg   %ax,%ax
  101f1e:	66 90                	xchg   %ax,%ax
  101f20:	66 90                	xchg   %ax,%ax
  101f22:	66 90                	xchg   %ax,%ax
  101f24:	66 90                	xchg   %ax,%ax
  101f26:	66 90                	xchg   %ax,%ax
  101f28:	66 90                	xchg   %ax,%ax
  101f2a:	66 90                	xchg   %ax,%ax
  101f2c:	66 90                	xchg   %ax,%ax
  101f2e:	66 90                	xchg   %ax,%ax
  101f30:	66 90                	xchg   %ax,%ax
  101f32:	66 90                	xchg   %ax,%ax
  101f34:	66 90                	xchg   %ax,%ax
  101f36:	66 90                	xchg   %ax,%ax
  101f38:	66 90                	xchg   %ax,%ax
  101f3a:	66 90                	xchg   %ax,%ax
  101f3c:	66 90                	xchg   %ax,%ax
  101f3e:	66 90                	xchg   %ax,%ax
  101f40:	66 90                	xchg   %ax,%ax
  101f42:	66 90                	xchg   %ax,%ax
  101f44:	66 90                	xchg   %ax,%ax
  101f46:	66 90                	xchg   %ax,%ax
  101f48:	66 90                	xchg   %ax,%ax
  101f4a:	66 90                	xchg   %ax,%ax
  101f4c:	66 90                	xchg   %ax,%ax
  101f4e:	66 90                	xchg   %ax,%ax
  101f50:	66 90                	xchg   %ax,%ax
  101f52:	66 90                	xchg   %ax,%ax
  101f54:	66 90                	xchg   %ax,%ax
  101f56:	66 90                	xchg   %ax,%ax
  101f58:	66 90                	xchg   %ax,%ax
  101f5a:	66 90                	xchg   %ax,%ax
  101f5c:	66 90                	xchg   %ax,%ax
  101f5e:	66 90                	xchg   %ax,%ax
  101f60:	66 90                	xchg   %ax,%ax
  101f62:	66 90                	xchg   %ax,%ax
  101f64:	66 90                	xchg   %ax,%ax
  101f66:	66 90                	xchg   %ax,%ax
  101f68:	66 90                	xchg   %ax,%ax
  101f6a:	66 90                	xchg   %ax,%ax
  101f6c:	66 90                	xchg   %ax,%ax
  101f6e:	66 90                	xchg   %ax,%ax
  101f70:	66 90                	xchg   %ax,%ax
  101f72:	66 90                	xchg   %ax,%ax
  101f74:	66 90                	xchg   %ax,%ax
  101f76:	66 90                	xchg   %ax,%ax
  101f78:	66 90                	xchg   %ax,%ax
  101f7a:	66 90                	xchg   %ax,%ax
  101f7c:	66 90                	xchg   %ax,%ax
  101f7e:	66 90                	xchg   %ax,%ax
  101f80:	66 90                	xchg   %ax,%ax
  101f82:	66 90                	xchg   %ax,%ax
  101f84:	66 90                	xchg   %ax,%ax
  101f86:	66 90                	xchg   %ax,%ax
  101f88:	66 90                	xchg   %ax,%ax
  101f8a:	66 90                	xchg   %ax,%ax
  101f8c:	66 90                	xchg   %ax,%ax
  101f8e:	66 90                	xchg   %ax,%ax
  101f90:	66 90                	xchg   %ax,%ax
  101f92:	66 90                	xchg   %ax,%ax
  101f94:	66 90                	xchg   %ax,%ax
  101f96:	66 90                	xchg   %ax,%ax
  101f98:	66 90                	xchg   %ax,%ax
  101f9a:	66 90                	xchg   %ax,%ax
  101f9c:	66 90                	xchg   %ax,%ax
  101f9e:	66 90                	xchg   %ax,%ax
  101fa0:	66 90                	xchg   %ax,%ax
  101fa2:	66 90                	xchg   %ax,%ax
  101fa4:	66 90                	xchg   %ax,%ax
  101fa6:	66 90                	xchg   %ax,%ax
  101fa8:	66 90                	xchg   %ax,%ax
  101faa:	66 90                	xchg   %ax,%ax
  101fac:	66 90                	xchg   %ax,%ax
  101fae:	66 90                	xchg   %ax,%ax
  101fb0:	66 90                	xchg   %ax,%ax
  101fb2:	66 90                	xchg   %ax,%ax
  101fb4:	66 90                	xchg   %ax,%ax
  101fb6:	66 90                	xchg   %ax,%ax
  101fb8:	66 90                	xchg   %ax,%ax
  101fba:	66 90                	xchg   %ax,%ax
  101fbc:	66 90                	xchg   %ax,%ax
  101fbe:	66 90                	xchg   %ax,%ax
  101fc0:	66 90                	xchg   %ax,%ax
  101fc2:	66 90                	xchg   %ax,%ax
  101fc4:	66 90                	xchg   %ax,%ax
  101fc6:	66 90                	xchg   %ax,%ax
  101fc8:	66 90                	xchg   %ax,%ax
  101fca:	66 90                	xchg   %ax,%ax
  101fcc:	66 90                	xchg   %ax,%ax
  101fce:	66 90                	xchg   %ax,%ax
  101fd0:	66 90                	xchg   %ax,%ax
  101fd2:	66 90                	xchg   %ax,%ax
  101fd4:	66 90                	xchg   %ax,%ax
  101fd6:	66 90                	xchg   %ax,%ax
  101fd8:	66 90                	xchg   %ax,%ax
  101fda:	66 90                	xchg   %ax,%ax
  101fdc:	66 90                	xchg   %ax,%ax
  101fde:	66 90                	xchg   %ax,%ax
  101fe0:	66 90                	xchg   %ax,%ax
  101fe2:	66 90                	xchg   %ax,%ax
  101fe4:	66 90                	xchg   %ax,%ax
  101fe6:	66 90                	xchg   %ax,%ax
  101fe8:	66 90                	xchg   %ax,%ax
  101fea:	66 90                	xchg   %ax,%ax
  101fec:	66 90                	xchg   %ax,%ax
  101fee:	66 90                	xchg   %ax,%ax
  101ff0:	66 90                	xchg   %ax,%ax
  101ff2:	66 90                	xchg   %ax,%ax
  101ff4:	66 90                	xchg   %ax,%ax
  101ff6:	66 90                	xchg   %ax,%ax
  101ff8:	66 90                	xchg   %ax,%ax
  101ffa:	66 90                	xchg   %ax,%ax
  101ffc:	66 90                	xchg   %ax,%ax
  101ffe:	66 90                	xchg   %ax,%ax
